/* Callback.java
 *
 * Generated by java-pp.pl from Callback.java
 * on Mon Jan  8 11:40:55 EST 2001

 * Copyright Goldin-Rudahl Associates
 *
 * $Id: Callback.java,v 1.1 2001/11/30 18:03:09 goldin Exp $
 * $Log: Callback.java,v $
 * Revision 1.1  2001/11/30 18:03:09  goldin
 * Moved most of the UI basic components to the com.grs.gui package
 *
 * Revision 1.3  2001/11/05 13:59:14  goldin
 * Put UI code in a package
 *
 * Revision 1.2  2001/01/12 19:10:21  goldin
 * Completed implementation of basic control types, added validation and callback support, key handling
 *
 * Revision 1.1  2001/01/08 19:34:42  goldin
 * Initial population for new DRAGON-Java UI
 *
 */

package com.grs.gui;

/** This interface defines the method that must be implemented for all
*   callbacks. Callbacks are used to modify the contents or enablement
*   of other panel fields based on the value in the current field.
* @author  goldin
* @version  Mon Jan 08 11:36:01 EST 2001
*/
public interface Callback 
    {
    
    //********************************************************************
      /** Primary method of a callback class. Modifies other fields in a
       *   DragonPanel based on the current value in the 0.0 The
       *   DragonPanel can be accessed via its reference in the
       *   DragonField object.
       * @param  field Field whose value will determine the
       *   effects of the callback.
       */

    public void executeCallback(DragonField field);
    
    }

// End of Callback.java

