/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_grs_gui_DriveTester */

#ifndef _Included_com_grs_gui_DriveTester
#define _Included_com_grs_gui_DriveTester
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_grs_gui_DriveTester
 * Method:    CheckDrive
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_grs_gui_DriveTester_CheckDrive
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
