/* DefectiveStructureException.java
 * kurt rudahl 10/27/2001
 * copyright goldin-rudahl associates
 * purpose:  Some structure is missing a required element
 **************************************************************************
 * $Id: DefectiveStructureException.java,v 1.2 2005/02/06 08:21:59 goldin Exp $
 * $Log: DefectiveStructureException.java,v $
 * Revision 1.2  2005/02/06 08:21:59  goldin
 * Fix javadoc warnings
 *
 * Revision 1.1  2001/10/27 13:13:31  rudahl
 * initial despoit, from tower. Not yet working
 *
 **************************************************************************
 * history 10/27/2001   created
 *                      Generated by Together
 */

package com.grs.metricCanvas;

/**
 * Some structure is missing a required element
 */
public class DefectiveStructureException extends Exception 
    {
    DefectiveStructureException() { super(); }
    DefectiveStructureException(String msg) { super(msg); }
    }
