/* Metric.java
 * kurt rudahl 10/26/2001
 * copyright goldin-rudahl associates
 * purpose: transform a single coordinate
 *************************************************************************
 * $Id: Metric.java,v 1.3 2001/11/02 19:13:45 goldin Exp $
 * $Log: Metric.java,v $
 * Revision 1.3  2001/11/02 19:13:45  goldin
 * Add unmap function
 *
 * Revision 1.2  2001/10/27 17:32:37  rudahl
 * actually made it work, for Rulers
 *
 * Revision 1.1  2001/10/27 13:13:31  rudahl
 * initial despoit, from tower. Not yet working
 *
 *************************************************************************
 * history 10/26/2001   created
 *                      Generated by Together
 */

package com.grs.metricCanvas;

/**
 * transform a single coordinate
 */
public interface Metric
    {

      /** specify the minimum to maximum possible coordinate values
       *  (closed interval; min < max)
       */
    void setRange(double minInput, double maxInput, 
		  int minOutput, int maxOutput);

      /** remap the specified 1-dimensional point to conform to
       *  this metric. 
       */
    int remap(double point);

      /** reverse the mapping. Given an output point, map to
       * input values.
       */
    double unmap(int iPoint);

    }
