#include "drelease.h"
ID_ IMG_HDR_ID[]=
  "\0@(#) " __FILE__ "  $Revision: 1.63 $$Date: 2008/08/09 05:25:56 $";
D_REL_IDSTR;
/*-------------------------------------------------------------
 *	   IMG_HDR.C	read/write image headers
 *
 *	Copyright 1999-2008 Kurt Rudahl and Sally Goldin
 *
 *	All rights are reserved. Copying or other reproduction of
 *	this program except for archival purposes is prohibited
 *	without the prior written consent of Goldin-Rudahl Associates.
 *
 *			  RESTRICTED RIGHTS LEGEND
 *
 *	Use, duplication, or disclosure by the U.S. Government
 *	is subject to restrictions as set forth in
 *	paragraph (b) (3) (B) of the Rights in Technical
 *	Data and Computer Software clause in DAR 7-104.9(a).
 *
 *	The moral right of the copyright holder is hereby asserted
 *
 ***************************************************
 *  $Id: img_hdr.c,v 1.63 2008/08/09 05:25:56 rudahl Exp $
 *  $Log: img_hdr.c,v $
 *  Revision 1.63  2008/08/09 05:25:56  rudahl
 *  now rose.a generated by libsrc/common
 *
 *  Revision 1.62  2007/08/02 12:43:57  rudahl
 *  cleanup
 *
 *  Revision 1.61  2005/12/10 11:36:53  rudahl
 *  fixing some of the double-tilde comments
 *
 *  Revision 1.60  2005/09/17 05:29:20  rudahl
 *  improved dump
 *
 *  Revision 1.59  2005/08/02 02:11:06  rudahl
 *  re-enabled DumpHeader temporarily
 *
 *  Revision 1.58  2005/06/27 11:47:25  rudahl
 *  added some access fns, improved dump
 *
 *  Revision 1.57  2005/03/27 12:48:42  rudahl
 *  tracing fixes
 *
 *  Revision 1.56  2005/03/19 06:31:51  rudahl
 *  CVS moved from windu; maybe some history lost
 *
 *  Revision 1.58  2005/03/10 23:20:29  rudahl
 *  SetupImage mostly dead
 *
 *  Revision 1.57  2005/03/10 04:28:01  rudahl
 *  fixes for writing
 *
 *  Revision 1.56  2005/03/10 00:06:29  rudahl
 *  added imageHdr.h
 *
 *  Revision 1.55  2005/03/01 16:03:30  rudahl
 *  fix return value
 *
 *  Revision 1.54  2005/02/23 20:36:59  rudahl
 *  revising grsproc1 for new Image usages
 *
 *  Revision 1.53  2005/02/23 18:21:31  rudahl
 *  new update, wrapper fns; moved from hdrstats to dhead
 *
 *  Revision 1.52  2005/02/20 17:09:41  rudahl
 *  prelim create IMAGEHDR accessor fns
 *
 *  Revision 1.51  2005/02/15 20:26:16  rudahl
 *  now they compile, but maybe not correct
 *
 *  Revision 1.50  2005/02/03 16:07:19  rudahl
 *  initial support for multi-resolution formats
 *
 *  Revision 1.49  2005/01/30 03:45:21  rudahl
 *  using C fns for logTrace
 *
 *  Revision 1.48  2005/01/30 01:54:30  rudahl
 *  cleanup for v 5.5
 *
 *  Revision 1.47  2004/11/30 10:01:15  rudahl
 *  improve tracing
 *
 *  Revision 1.46  2004/11/30 03:34:25  rudahl
 *  adapt to Mingw 3.4.2 compiler
 *
 *  Revision 1.45  2002/09/14 22:09:03  rudahl
 *  fixup SynchHisto
 *
 *  Revision 1.44  2002/09/11 23:54:54  rudahl
 *  defensively, added code to convert any HEADER strings
 *  which might happen to have weird values into pure ASCII
 *
 *  Revision 1.43  2002/09/09 16:45:31  rudahl
 *  changed img::GetHeaderInfo
 *
 *  Revision 1.42  2002/09/05 18:56:36  goldin
 *  Remove some tracing
 *
 *  Revision 1.41  2002/09/05 00:45:59  rudahl
 *  work around keyed images
 *
 *  Revision 1.40  2002/08/31 23:03:27  rudahl
 *  adding classnamelen fields; improving dump
 *
 *  Revision 1.39  2002/08/30 20:33:40  rudahl
 *  added a couple of Image fields
 *
 *  Revision 1.38  2002/08/28 16:10:45  rudahl
 *  improved dump, zero
 *
 *  Revision 1.37  2002/07/22 20:15:54  goldin
 *  Test for null input in access functions
 *
 *  Revision 1.36  2002/07/22 16:58:23  goldin
 *  Change init to return zero status if all ok
 *
 *  Revision 1.35  2002/07/20 00:23:12  rudahl
 *  revs to IMAGE struct; add init(pImage)
 *
 *  Revision 1.34  2002/07/19 14:39:23  rudahl
 *  expanded set of cpp wrapper fnns; purged
 *
 *  Revision 1.33  2002/07/13 00:36:37  rudahl
 *  continue to impl. Image class
 *
 *  Revision 1.32  2002/07/12 00:11:47  rudahl
 *  implemented Image class
 *
 *  Revision 1.31  2002/07/05 23:37:34  goldin
 *  Continue work on keyed file functionality
 *
 *  Revision 1.30  2002/07/01 18:38:43  goldin
 *  Factor out and generalize components of SetupMainAndMask
 *
 *  Revision 1.29  2002/07/01 14:26:04  rudahl
 *  cleanup & rev'd tracing info
 *
 *  Revision 1.28  2002/06/25 13:54:53  rudahl
 *  excluded some unused from 16-bit
 *
 *  Revision 1.27  2002/06/25 00:32:37  rudahl
 *  got rid of vfile stuff in 16-bits; fixed KeyTable
 *
 *  Revision 1.26  2002/06/18 18:51:03  rudahl
 *  fixed problems with CalculateKeyTable
 *
 *  Revision 1.25  2002/06/17 14:54:20  goldin
 *  Move call to CalculateKeyTable
 *
 *  Revision 1.24  2002/06/14 23:54:39  goldin
 *  Added new function to compute key remapping table
 *
 *  Revision 1.23  2002/05/21 20:44:10  rudahl
 *  added more IMAGE initialization
 *
 *  Revision 1.22  2002/05/15 15:50:35  rudahl
 *  1. not compiled in small model (dgraph)
 *  2. convert to using CalcImageScale
 *  3. cleanup
 *
 *  Revision 1.21  2002/05/08 00:12:20  rudahl
 *  new header version * fields
 *
 *  Revision 1.20  2002/05/03 01:36:24  rudahl
 *  no loger an error if file bigger than calc'd
 *
 *  Revision 1.19  2002/04/30 01:14:29  rudahl
 *  fixed/improved a lot around GetImageFile
 *
 *  Revision 1.18  2002/04/09 21:31:33  rudahl
 *  adapt for long filenames
 *
 *  Revision 1.17  2002/02/08 20:27:59  rudahl
 *  fixed some tracing; cleanup
 *
 *  Revision 1.16  2002/01/30 13:10:09  rudahl
 *  made ConvertHeaderClassnames public
 *
 *  Revision 1.15  2002/01/15 17:24:30  rudahl
 *  moved worklines etc from basemem to img_acc
 *
 *  Revision 1.14  2001/10/02 15:58:38  rudahl
 *  some rewrite for 32-bits
 *
 *  Revision 1.13  2001/08/22 18:22:27  rudahl
 *  fixup for gcc
 *
 *  Revision 1.12  2000/08/06 02:15:20  rudahl
 *  fix to setting hdr.fields.source
 *
 *  Revision 1.11  2000/07/27 22:40:17  rudahl
 *  added limits.h to fix MSVC8 problem
 *
 *  Revision 1.10  2000/06/30 13:49:16  rudahl
 *  improved debug messages
 *
 *  Revision 1.9  2000/06/05 23:54:42  rudahl
 *  got rid of g_assert for win32
 *
 *  Revision 1.8  2000/05/30 01:04:32  rudahl
 *  some conditionals for WIN
 *
 *  Revision 1.6  1999/04/28 15:50:58  rudahl
 *  modified to support reinitialization of img memory in the DLL for each classification
 *
 *  Revision 1.5  1999/04/27 13:34:53  rudahl
 *  improved error checking in MapIHEAD
 *
 *  Revision 1.4  1999/04/21 14:28:38  rudahl
 *  centralizing IHEAD and IMAGE ops
 *
 *  Revision 1.3  1999/04/17 19:28:37  rudahl
 *  getting away from vfiles
 *
 *  Revision 1.2  1999/04/16 18:05:38  rudahl
 *  revising IHEAD and IMAGE functions
 *
 *  Revision 1.1  1999/03/31 01:55:02  rudahl
 *  moving image file loading from vfiles to disk files
 *
 *
 ***************************************************
 *  This file contains routines intended for use in the DRAGON
 *  image processing program. It retrieves header info from an image file,
 *  and in future will create same. Its primary use is as an overlay 
 *  in CGATE, to provide the parameters needed by the fns in IMG_ACC.C;
 *  however it should be able to be used in utilties and in Windows pgms.
 *  Prototypes etc are in IMG_ACC.H.
 *
 *----- History  -----------------------------------*
 *
 *	Developers
 * 		ktr	Kurt Rudahl
 *		seg	Sally Goldin
 *		(add more names here)
 * 5.0	3/30/99 ktr	created
 *      6/5/00 ktr      got rid of g_assert for win32
 *	4/9/02 ktr	adapted to long filenames by eliminating some buffers
 * 			and making others long in 32-bits
 * 5.4	11/29/2004 ktr	adapt for Mingw
 * 5.7 	2005-12-9 ktr	cleaned out the commented-out fns
 * 5.11	2007-5-9 ktr	cleanup
 *------------------------------------------------------------------*
 */

#include <limits.h>
#include <stdarg.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <time.h>

#if ! defined __GCC__ && ! defined __MINGCC__
#include <dos.h>
#include <io.h>
#endif
#include <stddef.h>	/* for offsetof() */

#include "dtypes.h"
#include "dlimits.h"
#include "dragon-errors.h"
#include "i18n.h"
#include "files.h"

#include "ob.h"
#include "dragonOb.h"
#include "logger.h"
#include "dhead.h"
#include "imageHdr.h"
#include "img.h"
#include "img_acc.h"

// put decl here for GCC's comfort

void IMG_HDR_C() {}

	/* get read-only histo info */
const void * GetImageHistoInfo(const IMAGE * pImage,
			       ushort * puHistPtrCount,
			       ushort * puHistPtrBinsize)
    {
    Image * pImg = (pImage == NULL) ? NULL : pImage->pImageObj;
    const void * pRetval = NULL;
    if (pImg != NULL)
	{
	pRetval = pImage->histptr;
	if (puHistPtrCount != NULL)
	    *puHistPtrCount = pImg->m_uHistPtrCount;
	if (puHistPtrBinsize != NULL)
	    *puHistPtrBinsize = pImg->m_uHistPtrBinsize;
	}
    return pRetval;
    }

/**
 * debugging function - dump image structure info to trace
 * file.
 * @param iImgNdx  Which image to dump
 */
// #ifdef NOMORE reinstated2005-8-1 - used by server
void DumpImage(const int iImgNdx)
    {
    Image * pImg = GetImagePtr(iImgNdx)->pImageObj;
    if (pImg != NULL)
	logTrace(pImg->dump(1,"img_hdr::DumpImage"));
    logTrace("DumpImage: IHEADsz=%d IMAGEsz=%d",sizeof(IHEAD),sizeof(IMAGE));
    }

void IMG_HDR_C_END() { puts(FIL_ID); }
