/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_grs_dragon_installer_InstallFileManager */

#ifndef _Included_com_grs_dragon_installer_InstallFileManager
#define _Included_com_grs_dragon_installer_InstallFileManager
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_grs_dragon_installer_InstallFileManager
 * Method:    GetFreeDiskSpace
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_com_grs_dragon_installer_InstallFileManager_GetFreeDiskSpace
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_grs_dragon_installer_InstallFileManager
 * Method:    ChangeCurrentDirectory
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_grs_dragon_installer_InstallFileManager_ChangeCurrentDirectory
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
/* Header for class com_grs_dragon_installer_InstallFileManager_FileChecker */

#ifndef _Included_com_grs_dragon_installer_InstallFileManager_FileChecker
#define _Included_com_grs_dragon_installer_InstallFileManager_FileChecker
#ifdef __cplusplus
extern "C" {
#endif
#undef com_grs_dragon_installer_InstallFileManager_FileChecker_MIN_PRIORITY
#define com_grs_dragon_installer_InstallFileManager_FileChecker_MIN_PRIORITY 1L
#undef com_grs_dragon_installer_InstallFileManager_FileChecker_NORM_PRIORITY
#define com_grs_dragon_installer_InstallFileManager_FileChecker_NORM_PRIORITY 5L
#undef com_grs_dragon_installer_InstallFileManager_FileChecker_MAX_PRIORITY
#define com_grs_dragon_installer_InstallFileManager_FileChecker_MAX_PRIORITY 10L
#ifdef __cplusplus
}
#endif
#endif
/* Header for class com_grs_dragon_installer_InstallFileManager_FileCopier */

#ifndef _Included_com_grs_dragon_installer_InstallFileManager_FileCopier
#define _Included_com_grs_dragon_installer_InstallFileManager_FileCopier
#ifdef __cplusplus
extern "C" {
#endif
#undef com_grs_dragon_installer_InstallFileManager_FileCopier_MIN_PRIORITY
#define com_grs_dragon_installer_InstallFileManager_FileCopier_MIN_PRIORITY 1L
#undef com_grs_dragon_installer_InstallFileManager_FileCopier_NORM_PRIORITY
#define com_grs_dragon_installer_InstallFileManager_FileCopier_NORM_PRIORITY 5L
#undef com_grs_dragon_installer_InstallFileManager_FileCopier_MAX_PRIORITY
#define com_grs_dragon_installer_InstallFileManager_FileCopier_MAX_PRIORITY 10L
#ifdef __cplusplus
}
#endif
#endif
/* Header for class com_grs_dragon_installer_InstallFileManager_FileCopySpec */

#ifndef _Included_com_grs_dragon_installer_InstallFileManager_FileCopySpec
#define _Included_com_grs_dragon_installer_InstallFileManager_FileCopySpec
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
