/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_grs_dragon_installer_SerialNumValidator */

#ifndef _Included_com_grs_dragon_installer_SerialNumValidator
#define _Included_com_grs_dragon_installer_SerialNumValidator
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_grs_dragon_installer_SerialNumValidator
 * Method:    isSerialValid
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_grs_dragon_installer_SerialNumValidator_isSerialValid
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_grs_dragon_installer_SerialNumValidator
 * Method:    needsKey
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_grs_dragon_installer_SerialNumValidator_needsKey
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
