/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_grs_dragon_common_PlatformSpecific */

#ifndef _Included_com_grs_dragon_common_PlatformSpecific
#define _Included_com_grs_dragon_common_PlatformSpecific
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_grs_dragon_common_PlatformSpecific
 * Method:    recordWindowByTitle
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_grs_dragon_common_PlatformSpecific_recordWindowByTitle
  (JNIEnv *, jclass, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
