/********************************************************
 * filename 855-uni.h
 *
 *  C header file - character cross reference table
 *  Unicode values for codepage 855 indices 128-255
 *  Generated by make-header.pl from CP855.TXT on 2003 Apr 30
 *  Copyright (c) Goldin-Rudahl Associates
 *
 ********************************************************/
// #
// #    Name:     cp855_DOSCyrillic to Unicode table
// #    Unicode version: 2.0
// #    Table version: 2.00
// #    Table format:  Format A
// #    Date:          04/24/96
// #    Authors:       Lori Brownell <loribr@microsoft.com>
// #                   K.D. Chang    <a-kchang@microsoft.com>
// #    General notes: none
// #
// #    Format: Three tab-separated columns
// #        Column #1 is the cp855_DOSCyrillic code (in hex)
// #        Column #2 is the Unicode (in hex as 0xXXXX)
// #        Column #3 is the Unicode name (follows a comment sign, '#')
// #
// #    The entries are in cp855_DOSCyrillic order
// #

#ifndef CP_855_TO_UNI_TAB
#define CP_855_TO_UNI_TAB \
/* 0=' ' */ 	0x0000, 	/* #NULL */\
/* 1=' ' */ 	0x0001, 	/* #START OF HEADING */\
/* 2=' ' */ 	0x0002, 	/* #START OF TEXT */\
/* 3=' ' */ 	0x0003, 	/* #END OF TEXT */\
/* 4=' ' */ 	0x0004, 	/* #END OF TRANSMISSION */\
/* 5=' ' */ 	0x0005, 	/* #ENQUIRY */\
/* 6=' ' */ 	0x0006, 	/* #ACKNOWLEDGE */\
/* 7=' ' */ 	0x0007, 	/* #BELL */\
/* 8=' ' */ 	0x0008, 	/* #BACKSPACE */\
/* 9=' ' */ 	0x0009, 	/* #HORIZONTAL TABULATION */\
/* 10=' ' */ 	0x000a, 	/* #LINE FEED */\
/* 11=' ' */ 	0x000b, 	/* #VERTICAL TABULATION */\
/* 12=' ' */ 	0x000c, 	/* #FORM FEED */\
/* 13=' ' */ 	0x000d, 	/* #CARRIAGE RETURN */\
/* 14=' ' */ 	0x000e, 	/* #SHIFT OUT */\
/* 15=' ' */ 	0x000f, 	/* #SHIFT IN */\
/* 16=' ' */ 	0x0010, 	/* #DATA LINK ESCAPE */\
/* 17=' ' */ 	0x0011, 	/* #DEVICE CONTROL ONE */\
/* 18=' ' */ 	0x0012, 	/* #DEVICE CONTROL TWO */\
/* 19=' ' */ 	0x0013, 	/* #DEVICE CONTROL THREE */\
/* 20=' ' */ 	0x0014, 	/* #DEVICE CONTROL FOUR */\
/* 21=' ' */ 	0x0015, 	/* #NEGATIVE ACKNOWLEDGE */\
/* 22=' ' */ 	0x0016, 	/* #SYNCHRONOUS IDLE */\
/* 23=' ' */ 	0x0017, 	/* #END OF TRANSMISSION BLOCK */\
/* 24=' ' */ 	0x0018, 	/* #CANCEL */\
/* 25=' ' */ 	0x0019, 	/* #END OF MEDIUM */\
/* 26=' ' */ 	0x001a, 	/* #SUBSTITUTE */\
/* 27=' ' */ 	0x001b, 	/* #ESCAPE */\
/* 28=' ' */ 	0x001c, 	/* #FILE SEPARATOR */\
/* 29=' ' */ 	0x001d, 	/* #GROUP SEPARATOR */\
/* 30=' ' */ 	0x001e, 	/* #RECORD SEPARATOR */\
/* 31=' ' */ 	0x001f, 	/* #UNIT SEPARATOR */\
/* 32=' ' */ 	0x0020, 	/* #SPACE */\
/* 33='!' */ 	0x0021, 	/* #EXCLAMATION MARK */\
/* 34='"' */ 	0x0022, 	/* #QUOTATION MARK */\
/* 35='#' */ 	0x0023, 	/* #NUMBER SIGN */\
/* 36='$' */ 	0x0024, 	/* #DOLLAR SIGN */\
/* 37='%' */ 	0x0025, 	/* #PERCENT SIGN */\
/* 38='&' */ 	0x0026, 	/* #AMPERSAND */\
/* 39=''' */ 	0x0027, 	/* #APOSTROPHE */\
/* 40='(' */ 	0x0028, 	/* #LEFT PARENTHESIS */\
/* 41=')' */ 	0x0029, 	/* #RIGHT PARENTHESIS */\
/* 42='*' */ 	0x002a, 	/* #ASTERISK */\
/* 43='+' */ 	0x002b, 	/* #PLUS SIGN */\
/* 44=',' */ 	0x002c, 	/* #COMMA */\
/* 45='-' */ 	0x002d, 	/* #HYPHEN-MINUS */\
/* 46='.' */ 	0x002e, 	/* #FULL STOP */\
/* 47='/' */ 	0x002f, 	/* #SOLIDUS */\
/* 48='0' */ 	0x0030, 	/* #DIGIT ZERO */\
/* 49='1' */ 	0x0031, 	/* #DIGIT ONE */\
/* 50='2' */ 	0x0032, 	/* #DIGIT TWO */\
/* 51='3' */ 	0x0033, 	/* #DIGIT THREE */\
/* 52='4' */ 	0x0034, 	/* #DIGIT FOUR */\
/* 53='5' */ 	0x0035, 	/* #DIGIT FIVE */\
/* 54='6' */ 	0x0036, 	/* #DIGIT SIX */\
/* 55='7' */ 	0x0037, 	/* #DIGIT SEVEN */\
/* 56='8' */ 	0x0038, 	/* #DIGIT EIGHT */\
/* 57='9' */ 	0x0039, 	/* #DIGIT NINE */\
/* 58=':' */ 	0x003a, 	/* #COLON */\
/* 59=';' */ 	0x003b, 	/* #SEMICOLON */\
/* 60='<' */ 	0x003c, 	/* #LESS-THAN SIGN */\
/* 61='=' */ 	0x003d, 	/* #EQUALS SIGN */\
/* 62='>' */ 	0x003e, 	/* #GREATER-THAN SIGN */\
/* 63='?' */ 	0x003f, 	/* #QUESTION MARK */\
/* 64='@' */ 	0x0040, 	/* #COMMERCIAL AT */\
/* 65='A' */ 	0x0041, 	/* #LATIN CAPITAL LETTER A */\
/* 66='B' */ 	0x0042, 	/* #LATIN CAPITAL LETTER B */\
/* 67='C' */ 	0x0043, 	/* #LATIN CAPITAL LETTER C */\
/* 68='D' */ 	0x0044, 	/* #LATIN CAPITAL LETTER D */\
/* 69='E' */ 	0x0045, 	/* #LATIN CAPITAL LETTER E */\
/* 70='F' */ 	0x0046, 	/* #LATIN CAPITAL LETTER F */\
/* 71='G' */ 	0x0047, 	/* #LATIN CAPITAL LETTER G */\
/* 72='H' */ 	0x0048, 	/* #LATIN CAPITAL LETTER H */\
/* 73='I' */ 	0x0049, 	/* #LATIN CAPITAL LETTER I */\
/* 74='J' */ 	0x004a, 	/* #LATIN CAPITAL LETTER J */\
/* 75='K' */ 	0x004b, 	/* #LATIN CAPITAL LETTER K */\
/* 76='L' */ 	0x004c, 	/* #LATIN CAPITAL LETTER L */\
/* 77='M' */ 	0x004d, 	/* #LATIN CAPITAL LETTER M */\
/* 78='N' */ 	0x004e, 	/* #LATIN CAPITAL LETTER N */\
/* 79='O' */ 	0x004f, 	/* #LATIN CAPITAL LETTER O */\
/* 80='P' */ 	0x0050, 	/* #LATIN CAPITAL LETTER P */\
/* 81='Q' */ 	0x0051, 	/* #LATIN CAPITAL LETTER Q */\
/* 82='R' */ 	0x0052, 	/* #LATIN CAPITAL LETTER R */\
/* 83='S' */ 	0x0053, 	/* #LATIN CAPITAL LETTER S */\
/* 84='T' */ 	0x0054, 	/* #LATIN CAPITAL LETTER T */\
/* 85='U' */ 	0x0055, 	/* #LATIN CAPITAL LETTER U */\
/* 86='V' */ 	0x0056, 	/* #LATIN CAPITAL LETTER V */\
/* 87='W' */ 	0x0057, 	/* #LATIN CAPITAL LETTER W */\
/* 88='X' */ 	0x0058, 	/* #LATIN CAPITAL LETTER X */\
/* 89='Y' */ 	0x0059, 	/* #LATIN CAPITAL LETTER Y */\
/* 90='Z' */ 	0x005a, 	/* #LATIN CAPITAL LETTER Z */\
/* 91='[' */ 	0x005b, 	/* #LEFT SQUARE BRACKET */\
/* 92='\' */ 	0x005c, 	/* #REVERSE SOLIDUS */\
/* 93=']' */ 	0x005d, 	/* #RIGHT SQUARE BRACKET */\
/* 94='^' */ 	0x005e, 	/* #CIRCUMFLEX ACCENT */\
/* 95='_' */ 	0x005f, 	/* #LOW LINE */\
/* 96='`' */ 	0x0060, 	/* #GRAVE ACCENT */\
/* 97='a' */ 	0x0061, 	/* #LATIN SMALL LETTER A */\
/* 98='b' */ 	0x0062, 	/* #LATIN SMALL LETTER B */\
/* 99='c' */ 	0x0063, 	/* #LATIN SMALL LETTER C */\
/* 100='d' */ 	0x0064, 	/* #LATIN SMALL LETTER D */\
/* 101='e' */ 	0x0065, 	/* #LATIN SMALL LETTER E */\
/* 102='f' */ 	0x0066, 	/* #LATIN SMALL LETTER F */\
/* 103='g' */ 	0x0067, 	/* #LATIN SMALL LETTER G */\
/* 104='h' */ 	0x0068, 	/* #LATIN SMALL LETTER H */\
/* 105='i' */ 	0x0069, 	/* #LATIN SMALL LETTER I */\
/* 106='j' */ 	0x006a, 	/* #LATIN SMALL LETTER J */\
/* 107='k' */ 	0x006b, 	/* #LATIN SMALL LETTER K */\
/* 108='l' */ 	0x006c, 	/* #LATIN SMALL LETTER L */\
/* 109='m' */ 	0x006d, 	/* #LATIN SMALL LETTER M */\
/* 110='n' */ 	0x006e, 	/* #LATIN SMALL LETTER N */\
/* 111='o' */ 	0x006f, 	/* #LATIN SMALL LETTER O */\
/* 112='p' */ 	0x0070, 	/* #LATIN SMALL LETTER P */\
/* 113='q' */ 	0x0071, 	/* #LATIN SMALL LETTER Q */\
/* 114='r' */ 	0x0072, 	/* #LATIN SMALL LETTER R */\
/* 115='s' */ 	0x0073, 	/* #LATIN SMALL LETTER S */\
/* 116='t' */ 	0x0074, 	/* #LATIN SMALL LETTER T */\
/* 117='u' */ 	0x0075, 	/* #LATIN SMALL LETTER U */\
/* 118='v' */ 	0x0076, 	/* #LATIN SMALL LETTER V */\
/* 119='w' */ 	0x0077, 	/* #LATIN SMALL LETTER W */\
/* 120='x' */ 	0x0078, 	/* #LATIN SMALL LETTER X */\
/* 121='y' */ 	0x0079, 	/* #LATIN SMALL LETTER Y */\
/* 122='z' */ 	0x007a, 	/* #LATIN SMALL LETTER Z */\
/* 123='{' */ 	0x007b, 	/* #LEFT CURLY BRACKET */\
/* 124='|' */ 	0x007c, 	/* #VERTICAL LINE */\
/* 125='}' */ 	0x007d, 	/* #RIGHT CURLY BRACKET */\
/* 126='~' */ 	0x007e, 	/* #TILDE */\
/* 127='' */ 	0x007f, 	/* #DELETE */\
/* 128='Ä' */ 	0x0452, 	/* #CYRILLIC SMALL LETTER DJE */\
/* 129='Å' */ 	0x0402, 	/* #CYRILLIC CAPITAL LETTER DJE */\
/* 130='Ç' */ 	0x0453, 	/* #CYRILLIC SMALL LETTER GJE */\
/* 131='É' */ 	0x0403, 	/* #CYRILLIC CAPITAL LETTER GJE */\
/* 132='Ñ' */ 	0x0451, 	/* #CYRILLIC SMALL LETTER IO */\
/* 133='Ö' */ 	0x0401, 	/* #CYRILLIC CAPITAL LETTER IO */\
/* 134='Ü' */ 	0x0454, 	/* #CYRILLIC SMALL LETTER UKRAINIAN IE */\
/* 135='á' */ 	0x0404, 	/* #CYRILLIC CAPITAL LETTER UKRAINIAN IE */\
/* 136='à' */ 	0x0455, 	/* #CYRILLIC SMALL LETTER DZE */\
/* 137='â' */ 	0x0405, 	/* #CYRILLIC CAPITAL LETTER DZE */\
/* 138='ä' */ 	0x0456, 	/* #CYRILLIC SMALL LETTER BYELORUSSIAN-UKRAINIAN I */\
/* 139='ã' */ 	0x0406, 	/* #CYRILLIC CAPITAL LETTER BYELORUSSIAN-UKRAINIAN I */\
/* 140='å' */ 	0x0457, 	/* #CYRILLIC SMALL LETTER YI */\
/* 141='ç' */ 	0x0407, 	/* #CYRILLIC CAPITAL LETTER YI */\
/* 142='é' */ 	0x0458, 	/* #CYRILLIC SMALL LETTER JE */\
/* 143='è' */ 	0x0408, 	/* #CYRILLIC CAPITAL LETTER JE */\
/* 144='ê' */ 	0x0459, 	/* #CYRILLIC SMALL LETTER LJE */\
/* 145='ë' */ 	0x0409, 	/* #CYRILLIC CAPITAL LETTER LJE */\
/* 146='í' */ 	0x045a, 	/* #CYRILLIC SMALL LETTER NJE */\
/* 147='ì' */ 	0x040a, 	/* #CYRILLIC CAPITAL LETTER NJE */\
/* 148='î' */ 	0x045b, 	/* #CYRILLIC SMALL LETTER TSHE */\
/* 149='ï' */ 	0x040b, 	/* #CYRILLIC CAPITAL LETTER TSHE */\
/* 150='ñ' */ 	0x045c, 	/* #CYRILLIC SMALL LETTER KJE */\
/* 151='ó' */ 	0x040c, 	/* #CYRILLIC CAPITAL LETTER KJE */\
/* 152='ò' */ 	0x045e, 	/* #CYRILLIC SMALL LETTER SHORT U */\
/* 153='ô' */ 	0x040e, 	/* #CYRILLIC CAPITAL LETTER SHORT U */\
/* 154='ö' */ 	0x045f, 	/* #CYRILLIC SMALL LETTER DZHE */\
/* 155='õ' */ 	0x040f, 	/* #CYRILLIC CAPITAL LETTER DZHE */\
/* 156='ú' */ 	0x044e, 	/* #CYRILLIC SMALL LETTER YU */\
/* 157='ù' */ 	0x042e, 	/* #CYRILLIC CAPITAL LETTER YU */\
/* 158='û' */ 	0x044a, 	/* #CYRILLIC SMALL LETTER HARD SIGN */\
/* 159='ü' */ 	0x042a, 	/* #CYRILLIC CAPITAL LETTER HARD SIGN */\
/* 160='†' */ 	0x0430, 	/* #CYRILLIC SMALL LETTER A */\
/* 161='°' */ 	0x0410, 	/* #CYRILLIC CAPITAL LETTER A */\
/* 162='¢' */ 	0x0431, 	/* #CYRILLIC SMALL LETTER BE */\
/* 163='£' */ 	0x0411, 	/* #CYRILLIC CAPITAL LETTER BE */\
/* 164='§' */ 	0x0446, 	/* #CYRILLIC SMALL LETTER TSE */\
/* 165='•' */ 	0x0426, 	/* #CYRILLIC CAPITAL LETTER TSE */\
/* 166='¶' */ 	0x0434, 	/* #CYRILLIC SMALL LETTER DE */\
/* 167='ß' */ 	0x0414, 	/* #CYRILLIC CAPITAL LETTER DE */\
/* 168='®' */ 	0x0435, 	/* #CYRILLIC SMALL LETTER IE */\
/* 169='©' */ 	0x0415, 	/* #CYRILLIC CAPITAL LETTER IE */\
/* 170='™' */ 	0x0444, 	/* #CYRILLIC SMALL LETTER EF */\
/* 171='´' */ 	0x0424, 	/* #CYRILLIC CAPITAL LETTER EF */\
/* 172='¨' */ 	0x0433, 	/* #CYRILLIC SMALL LETTER GHE */\
/* 173='≠' */ 	0x0413, 	/* #CYRILLIC CAPITAL LETTER GHE */\
/* 174='Æ' */ 	0x00ab, 	/* #LEFT-POINTING DOUBLE ANGLE QUOTATION MARK */\
/* 175='Ø' */ 	0x00bb, 	/* #RIGHT-POINTING DOUBLE ANGLE QUOTATION MARK */\
/* 176='∞' */ 	0x2591, 	/* #LIGHT SHADE */\
/* 177='±' */ 	0x2592, 	/* #MEDIUM SHADE */\
/* 178='≤' */ 	0x2593, 	/* #DARK SHADE */\
/* 179='≥' */ 	0x2502, 	/* #BOX DRAWINGS LIGHT VERTICAL */\
/* 180='¥' */ 	0x2524, 	/* #BOX DRAWINGS LIGHT VERTICAL AND LEFT */\
/* 181='µ' */ 	0x0445, 	/* #CYRILLIC SMALL LETTER HA */\
/* 182='∂' */ 	0x0425, 	/* #CYRILLIC CAPITAL LETTER HA */\
/* 183='∑' */ 	0x0438, 	/* #CYRILLIC SMALL LETTER I */\
/* 184='∏' */ 	0x0418, 	/* #CYRILLIC CAPITAL LETTER I */\
/* 185='π' */ 	0x2563, 	/* #BOX DRAWINGS DOUBLE VERTICAL AND LEFT */\
/* 186='∫' */ 	0x2551, 	/* #BOX DRAWINGS DOUBLE VERTICAL */\
/* 187='ª' */ 	0x2557, 	/* #BOX DRAWINGS DOUBLE DOWN AND LEFT */\
/* 188='º' */ 	0x255d, 	/* #BOX DRAWINGS DOUBLE UP AND LEFT */\
/* 189='Ω' */ 	0x0439, 	/* #CYRILLIC SMALL LETTER SHORT I */\
/* 190='æ' */ 	0x0419, 	/* #CYRILLIC CAPITAL LETTER SHORT I */\
/* 191='ø' */ 	0x2510, 	/* #BOX DRAWINGS LIGHT DOWN AND LEFT */\
/* 192='¿' */ 	0x2514, 	/* #BOX DRAWINGS LIGHT UP AND RIGHT */\
/* 193='¡' */ 	0x2534, 	/* #BOX DRAWINGS LIGHT UP AND HORIZONTAL */\
/* 194='¬' */ 	0x252c, 	/* #BOX DRAWINGS LIGHT DOWN AND HORIZONTAL */\
/* 195='√' */ 	0x251c, 	/* #BOX DRAWINGS LIGHT VERTICAL AND RIGHT */\
/* 196='ƒ' */ 	0x2500, 	/* #BOX DRAWINGS LIGHT HORIZONTAL */\
/* 197='≈' */ 	0x253c, 	/* #BOX DRAWINGS LIGHT VERTICAL AND HORIZONTAL */\
/* 198='∆' */ 	0x043a, 	/* #CYRILLIC SMALL LETTER KA */\
/* 199='«' */ 	0x041a, 	/* #CYRILLIC CAPITAL LETTER KA */\
/* 200='»' */ 	0x255a, 	/* #BOX DRAWINGS DOUBLE UP AND RIGHT */\
/* 201='…' */ 	0x2554, 	/* #BOX DRAWINGS DOUBLE DOWN AND RIGHT */\
/* 202=' ' */ 	0x2569, 	/* #BOX DRAWINGS DOUBLE UP AND HORIZONTAL */\
/* 203='À' */ 	0x2566, 	/* #BOX DRAWINGS DOUBLE DOWN AND HORIZONTAL */\
/* 204='Ã' */ 	0x2560, 	/* #BOX DRAWINGS DOUBLE VERTICAL AND RIGHT */\
/* 205='Õ' */ 	0x2550, 	/* #BOX DRAWINGS DOUBLE HORIZONTAL */\
/* 206='Œ' */ 	0x256c, 	/* #BOX DRAWINGS DOUBLE VERTICAL AND HORIZONTAL */\
/* 207='œ' */ 	0x00a4, 	/* #CURRENCY SIGN */\
/* 208='–' */ 	0x043b, 	/* #CYRILLIC SMALL LETTER EL */\
/* 209='—' */ 	0x041b, 	/* #CYRILLIC CAPITAL LETTER EL */\
/* 210='“' */ 	0x043c, 	/* #CYRILLIC SMALL LETTER EM */\
/* 211='”' */ 	0x041c, 	/* #CYRILLIC CAPITAL LETTER EM */\
/* 212='‘' */ 	0x043d, 	/* #CYRILLIC SMALL LETTER EN */\
/* 213='’' */ 	0x041d, 	/* #CYRILLIC CAPITAL LETTER EN */\
/* 214='÷' */ 	0x043e, 	/* #CYRILLIC SMALL LETTER O */\
/* 215='◊' */ 	0x041e, 	/* #CYRILLIC CAPITAL LETTER O */\
/* 216='ÿ' */ 	0x043f, 	/* #CYRILLIC SMALL LETTER PE */\
/* 217='Ÿ' */ 	0x2518, 	/* #BOX DRAWINGS LIGHT UP AND LEFT */\
/* 218='⁄' */ 	0x250c, 	/* #BOX DRAWINGS LIGHT DOWN AND RIGHT */\
/* 219='€' */ 	0x2588, 	/* #FULL BLOCK */\
/* 220='‹' */ 	0x2584, 	/* #LOWER HALF BLOCK */\
/* 221='›' */ 	0x041f, 	/* #CYRILLIC CAPITAL LETTER PE */\
/* 222='ﬁ' */ 	0x044f, 	/* #CYRILLIC SMALL LETTER YA */\
/* 223='ﬂ' */ 	0x2580, 	/* #UPPER HALF BLOCK */\
/* 224='‡' */ 	0x042f, 	/* #CYRILLIC CAPITAL LETTER YA */\
/* 225='·' */ 	0x0440, 	/* #CYRILLIC SMALL LETTER ER */\
/* 226='‚' */ 	0x0420, 	/* #CYRILLIC CAPITAL LETTER ER */\
/* 227='„' */ 	0x0441, 	/* #CYRILLIC SMALL LETTER ES */\
/* 228='‰' */ 	0x0421, 	/* #CYRILLIC CAPITAL LETTER ES */\
/* 229='Â' */ 	0x0442, 	/* #CYRILLIC SMALL LETTER TE */\
/* 230='Ê' */ 	0x0422, 	/* #CYRILLIC CAPITAL LETTER TE */\
/* 231='Á' */ 	0x0443, 	/* #CYRILLIC SMALL LETTER U */\
/* 232='Ë' */ 	0x0423, 	/* #CYRILLIC CAPITAL LETTER U */\
/* 233='È' */ 	0x0436, 	/* #CYRILLIC SMALL LETTER ZHE */\
/* 234='Í' */ 	0x0416, 	/* #CYRILLIC CAPITAL LETTER ZHE */\
/* 235='Î' */ 	0x0432, 	/* #CYRILLIC SMALL LETTER VE */\
/* 236='Ï' */ 	0x0412, 	/* #CYRILLIC CAPITAL LETTER VE */\
/* 237='Ì' */ 	0x044c, 	/* #CYRILLIC SMALL LETTER SOFT SIGN */\
/* 238='Ó' */ 	0x042c, 	/* #CYRILLIC CAPITAL LETTER SOFT SIGN */\
/* 239='Ô' */ 	0x2116, 	/* #NUMERO SIGN */\
/* 240='' */ 	0x00ad, 	/* #SOFT HYPHEN */\
/* 241='Ò' */ 	0x044b, 	/* #CYRILLIC SMALL LETTER YERU */\
/* 242='Ú' */ 	0x042b, 	/* #CYRILLIC CAPITAL LETTER YERU */\
/* 243='Û' */ 	0x0437, 	/* #CYRILLIC SMALL LETTER ZE */\
/* 244='Ù' */ 	0x0417, 	/* #CYRILLIC CAPITAL LETTER ZE */\
/* 245='ı' */ 	0x0448, 	/* #CYRILLIC SMALL LETTER SHA */\
/* 246='ˆ' */ 	0x0428, 	/* #CYRILLIC CAPITAL LETTER SHA */\
/* 247='˜' */ 	0x044d, 	/* #CYRILLIC SMALL LETTER E */\
/* 248='¯' */ 	0x042d, 	/* #CYRILLIC CAPITAL LETTER E */\
/* 249='˘' */ 	0x0449, 	/* #CYRILLIC SMALL LETTER SHCHA */\
/* 250='˙' */ 	0x0429, 	/* #CYRILLIC CAPITAL LETTER SHCHA */\
/* 251='˚' */ 	0x0447, 	/* #CYRILLIC SMALL LETTER CHE */\
/* 252='¸' */ 	0x0427, 	/* #CYRILLIC CAPITAL LETTER CHE */\
/* 253='˝' */ 	0x00a7, 	/* #SECTION SIGN */\
/* 254='˛' */ 	0x25a0, 	/* #BLACK SQUARE */\
/* 255='ˇ' */ 	0x00a0, 	/* #NO-BREAK SPACE */// 

#endif
