/********************************************************
 * filename 862-uni.h
 *
 *  C header file - character cross reference table
 *  Unicode values for codepage 862 indices 128-255
 *  Generated by make-header.pl from CP862.TXT on 2003 Apr 30
 *  Copyright (c) Goldin-Rudahl Associates
 *
 ********************************************************/
// #
// #    Name:     cp862_DOSHebrew to Unicode table
// #    Unicode version: 2.0
// #    Table version: 2.00
// #    Table format:  Format A
// #    Date:          04/24/96
// #    Authors:       Lori Brownell <loribr@microsoft.com>
// #                   K.D. Chang    <a-kchang@microsoft.com>
// #    General notes: none
// #
// #    Format: Three tab-separated columns
// #        Column #1 is the cp862_DOSHebrew code (in hex)
// #        Column #2 is the Unicode (in hex as 0xXXXX)
// #        Column #3 is the Unicode name (follows a comment sign, '#')
// #
// #    The entries are in cp862_DOSHebrew order
// #

#ifndef CP_862_TO_UNI_TAB
#define CP_862_TO_UNI_TAB \
/* 0=' ' */ 	0x0000, 	/* #NULL */\
/* 1=' ' */ 	0x0001, 	/* #START OF HEADING */\
/* 2=' ' */ 	0x0002, 	/* #START OF TEXT */\
/* 3=' ' */ 	0x0003, 	/* #END OF TEXT */\
/* 4=' ' */ 	0x0004, 	/* #END OF TRANSMISSION */\
/* 5=' ' */ 	0x0005, 	/* #ENQUIRY */\
/* 6=' ' */ 	0x0006, 	/* #ACKNOWLEDGE */\
/* 7=' ' */ 	0x0007, 	/* #BELL */\
/* 8=' ' */ 	0x0008, 	/* #BACKSPACE */\
/* 9=' ' */ 	0x0009, 	/* #HORIZONTAL TABULATION */\
/* 10=' ' */ 	0x000a, 	/* #LINE FEED */\
/* 11=' ' */ 	0x000b, 	/* #VERTICAL TABULATION */\
/* 12=' ' */ 	0x000c, 	/* #FORM FEED */\
/* 13=' ' */ 	0x000d, 	/* #CARRIAGE RETURN */\
/* 14=' ' */ 	0x000e, 	/* #SHIFT OUT */\
/* 15=' ' */ 	0x000f, 	/* #SHIFT IN */\
/* 16=' ' */ 	0x0010, 	/* #DATA LINK ESCAPE */\
/* 17=' ' */ 	0x0011, 	/* #DEVICE CONTROL ONE */\
/* 18=' ' */ 	0x0012, 	/* #DEVICE CONTROL TWO */\
/* 19=' ' */ 	0x0013, 	/* #DEVICE CONTROL THREE */\
/* 20=' ' */ 	0x0014, 	/* #DEVICE CONTROL FOUR */\
/* 21=' ' */ 	0x0015, 	/* #NEGATIVE ACKNOWLEDGE */\
/* 22=' ' */ 	0x0016, 	/* #SYNCHRONOUS IDLE */\
/* 23=' ' */ 	0x0017, 	/* #END OF TRANSMISSION BLOCK */\
/* 24=' ' */ 	0x0018, 	/* #CANCEL */\
/* 25=' ' */ 	0x0019, 	/* #END OF MEDIUM */\
/* 26=' ' */ 	0x001a, 	/* #SUBSTITUTE */\
/* 27=' ' */ 	0x001b, 	/* #ESCAPE */\
/* 28=' ' */ 	0x001c, 	/* #FILE SEPARATOR */\
/* 29=' ' */ 	0x001d, 	/* #GROUP SEPARATOR */\
/* 30=' ' */ 	0x001e, 	/* #RECORD SEPARATOR */\
/* 31=' ' */ 	0x001f, 	/* #UNIT SEPARATOR */\
/* 32=' ' */ 	0x0020, 	/* #SPACE */\
/* 33='!' */ 	0x0021, 	/* #EXCLAMATION MARK */\
/* 34='"' */ 	0x0022, 	/* #QUOTATION MARK */\
/* 35='#' */ 	0x0023, 	/* #NUMBER SIGN */\
/* 36='$' */ 	0x0024, 	/* #DOLLAR SIGN */\
/* 37='%' */ 	0x0025, 	/* #PERCENT SIGN */\
/* 38='&' */ 	0x0026, 	/* #AMPERSAND */\
/* 39=''' */ 	0x0027, 	/* #APOSTROPHE */\
/* 40='(' */ 	0x0028, 	/* #LEFT PARENTHESIS */\
/* 41=')' */ 	0x0029, 	/* #RIGHT PARENTHESIS */\
/* 42='*' */ 	0x002a, 	/* #ASTERISK */\
/* 43='+' */ 	0x002b, 	/* #PLUS SIGN */\
/* 44=',' */ 	0x002c, 	/* #COMMA */\
/* 45='-' */ 	0x002d, 	/* #HYPHEN-MINUS */\
/* 46='.' */ 	0x002e, 	/* #FULL STOP */\
/* 47='/' */ 	0x002f, 	/* #SOLIDUS */\
/* 48='0' */ 	0x0030, 	/* #DIGIT ZERO */\
/* 49='1' */ 	0x0031, 	/* #DIGIT ONE */\
/* 50='2' */ 	0x0032, 	/* #DIGIT TWO */\
/* 51='3' */ 	0x0033, 	/* #DIGIT THREE */\
/* 52='4' */ 	0x0034, 	/* #DIGIT FOUR */\
/* 53='5' */ 	0x0035, 	/* #DIGIT FIVE */\
/* 54='6' */ 	0x0036, 	/* #DIGIT SIX */\
/* 55='7' */ 	0x0037, 	/* #DIGIT SEVEN */\
/* 56='8' */ 	0x0038, 	/* #DIGIT EIGHT */\
/* 57='9' */ 	0x0039, 	/* #DIGIT NINE */\
/* 58=':' */ 	0x003a, 	/* #COLON */\
/* 59=';' */ 	0x003b, 	/* #SEMICOLON */\
/* 60='<' */ 	0x003c, 	/* #LESS-THAN SIGN */\
/* 61='=' */ 	0x003d, 	/* #EQUALS SIGN */\
/* 62='>' */ 	0x003e, 	/* #GREATER-THAN SIGN */\
/* 63='?' */ 	0x003f, 	/* #QUESTION MARK */\
/* 64='@' */ 	0x0040, 	/* #COMMERCIAL AT */\
/* 65='A' */ 	0x0041, 	/* #LATIN CAPITAL LETTER A */\
/* 66='B' */ 	0x0042, 	/* #LATIN CAPITAL LETTER B */\
/* 67='C' */ 	0x0043, 	/* #LATIN CAPITAL LETTER C */\
/* 68='D' */ 	0x0044, 	/* #LATIN CAPITAL LETTER D */\
/* 69='E' */ 	0x0045, 	/* #LATIN CAPITAL LETTER E */\
/* 70='F' */ 	0x0046, 	/* #LATIN CAPITAL LETTER F */\
/* 71='G' */ 	0x0047, 	/* #LATIN CAPITAL LETTER G */\
/* 72='H' */ 	0x0048, 	/* #LATIN CAPITAL LETTER H */\
/* 73='I' */ 	0x0049, 	/* #LATIN CAPITAL LETTER I */\
/* 74='J' */ 	0x004a, 	/* #LATIN CAPITAL LETTER J */\
/* 75='K' */ 	0x004b, 	/* #LATIN CAPITAL LETTER K */\
/* 76='L' */ 	0x004c, 	/* #LATIN CAPITAL LETTER L */\
/* 77='M' */ 	0x004d, 	/* #LATIN CAPITAL LETTER M */\
/* 78='N' */ 	0x004e, 	/* #LATIN CAPITAL LETTER N */\
/* 79='O' */ 	0x004f, 	/* #LATIN CAPITAL LETTER O */\
/* 80='P' */ 	0x0050, 	/* #LATIN CAPITAL LETTER P */\
/* 81='Q' */ 	0x0051, 	/* #LATIN CAPITAL LETTER Q */\
/* 82='R' */ 	0x0052, 	/* #LATIN CAPITAL LETTER R */\
/* 83='S' */ 	0x0053, 	/* #LATIN CAPITAL LETTER S */\
/* 84='T' */ 	0x0054, 	/* #LATIN CAPITAL LETTER T */\
/* 85='U' */ 	0x0055, 	/* #LATIN CAPITAL LETTER U */\
/* 86='V' */ 	0x0056, 	/* #LATIN CAPITAL LETTER V */\
/* 87='W' */ 	0x0057, 	/* #LATIN CAPITAL LETTER W */\
/* 88='X' */ 	0x0058, 	/* #LATIN CAPITAL LETTER X */\
/* 89='Y' */ 	0x0059, 	/* #LATIN CAPITAL LETTER Y */\
/* 90='Z' */ 	0x005a, 	/* #LATIN CAPITAL LETTER Z */\
/* 91='[' */ 	0x005b, 	/* #LEFT SQUARE BRACKET */\
/* 92='\' */ 	0x005c, 	/* #REVERSE SOLIDUS */\
/* 93=']' */ 	0x005d, 	/* #RIGHT SQUARE BRACKET */\
/* 94='^' */ 	0x005e, 	/* #CIRCUMFLEX ACCENT */\
/* 95='_' */ 	0x005f, 	/* #LOW LINE */\
/* 96='`' */ 	0x0060, 	/* #GRAVE ACCENT */\
/* 97='a' */ 	0x0061, 	/* #LATIN SMALL LETTER A */\
/* 98='b' */ 	0x0062, 	/* #LATIN SMALL LETTER B */\
/* 99='c' */ 	0x0063, 	/* #LATIN SMALL LETTER C */\
/* 100='d' */ 	0x0064, 	/* #LATIN SMALL LETTER D */\
/* 101='e' */ 	0x0065, 	/* #LATIN SMALL LETTER E */\
/* 102='f' */ 	0x0066, 	/* #LATIN SMALL LETTER F */\
/* 103='g' */ 	0x0067, 	/* #LATIN SMALL LETTER G */\
/* 104='h' */ 	0x0068, 	/* #LATIN SMALL LETTER H */\
/* 105='i' */ 	0x0069, 	/* #LATIN SMALL LETTER I */\
/* 106='j' */ 	0x006a, 	/* #LATIN SMALL LETTER J */\
/* 107='k' */ 	0x006b, 	/* #LATIN SMALL LETTER K */\
/* 108='l' */ 	0x006c, 	/* #LATIN SMALL LETTER L */\
/* 109='m' */ 	0x006d, 	/* #LATIN SMALL LETTER M */\
/* 110='n' */ 	0x006e, 	/* #LATIN SMALL LETTER N */\
/* 111='o' */ 	0x006f, 	/* #LATIN SMALL LETTER O */\
/* 112='p' */ 	0x0070, 	/* #LATIN SMALL LETTER P */\
/* 113='q' */ 	0x0071, 	/* #LATIN SMALL LETTER Q */\
/* 114='r' */ 	0x0072, 	/* #LATIN SMALL LETTER R */\
/* 115='s' */ 	0x0073, 	/* #LATIN SMALL LETTER S */\
/* 116='t' */ 	0x0074, 	/* #LATIN SMALL LETTER T */\
/* 117='u' */ 	0x0075, 	/* #LATIN SMALL LETTER U */\
/* 118='v' */ 	0x0076, 	/* #LATIN SMALL LETTER V */\
/* 119='w' */ 	0x0077, 	/* #LATIN SMALL LETTER W */\
/* 120='x' */ 	0x0078, 	/* #LATIN SMALL LETTER X */\
/* 121='y' */ 	0x0079, 	/* #LATIN SMALL LETTER Y */\
/* 122='z' */ 	0x007a, 	/* #LATIN SMALL LETTER Z */\
/* 123='{' */ 	0x007b, 	/* #LEFT CURLY BRACKET */\
/* 124='|' */ 	0x007c, 	/* #VERTICAL LINE */\
/* 125='}' */ 	0x007d, 	/* #RIGHT CURLY BRACKET */\
/* 126='~' */ 	0x007e, 	/* #TILDE */\
/* 127='' */ 	0x007f, 	/* #DELETE */\
/* 128='Ä' */ 	0x05d0, 	/* #HEBREW LETTER ALEF */\
/* 129='Å' */ 	0x05d1, 	/* #HEBREW LETTER BET */\
/* 130='Ç' */ 	0x05d2, 	/* #HEBREW LETTER GIMEL */\
/* 131='É' */ 	0x05d3, 	/* #HEBREW LETTER DALET */\
/* 132='Ñ' */ 	0x05d4, 	/* #HEBREW LETTER HE */\
/* 133='Ö' */ 	0x05d5, 	/* #HEBREW LETTER VAV */\
/* 134='Ü' */ 	0x05d6, 	/* #HEBREW LETTER ZAYIN */\
/* 135='á' */ 	0x05d7, 	/* #HEBREW LETTER HET */\
/* 136='à' */ 	0x05d8, 	/* #HEBREW LETTER TET */\
/* 137='â' */ 	0x05d9, 	/* #HEBREW LETTER YOD */\
/* 138='ä' */ 	0x05da, 	/* #HEBREW LETTER FINAL KAF */\
/* 139='ã' */ 	0x05db, 	/* #HEBREW LETTER KAF */\
/* 140='å' */ 	0x05dc, 	/* #HEBREW LETTER LAMED */\
/* 141='ç' */ 	0x05dd, 	/* #HEBREW LETTER FINAL MEM */\
/* 142='é' */ 	0x05de, 	/* #HEBREW LETTER MEM */\
/* 143='è' */ 	0x05df, 	/* #HEBREW LETTER FINAL NUN */\
/* 144='ê' */ 	0x05e0, 	/* #HEBREW LETTER NUN */\
/* 145='ë' */ 	0x05e1, 	/* #HEBREW LETTER SAMEKH */\
/* 146='í' */ 	0x05e2, 	/* #HEBREW LETTER AYIN */\
/* 147='ì' */ 	0x05e3, 	/* #HEBREW LETTER FINAL PE */\
/* 148='î' */ 	0x05e4, 	/* #HEBREW LETTER PE */\
/* 149='ï' */ 	0x05e5, 	/* #HEBREW LETTER FINAL TSADI */\
/* 150='ñ' */ 	0x05e6, 	/* #HEBREW LETTER TSADI */\
/* 151='ó' */ 	0x05e7, 	/* #HEBREW LETTER QOF */\
/* 152='ò' */ 	0x05e8, 	/* #HEBREW LETTER RESH */\
/* 153='ô' */ 	0x05e9, 	/* #HEBREW LETTER SHIN */\
/* 154='ö' */ 	0x05ea, 	/* #HEBREW LETTER TAV */\
/* 155='õ' */ 	0x00a2, 	/* #CENT SIGN */\
/* 156='ú' */ 	0x00a3, 	/* #POUND SIGN */\
/* 157='ù' */ 	0x00a5, 	/* #YEN SIGN */\
/* 158='û' */ 	0x20a7, 	/* #PESETA SIGN */\
/* 159='ü' */ 	0x0192, 	/* #LATIN SMALL LETTER F WITH HOOK */\
/* 160='†' */ 	0x00e1, 	/* #LATIN SMALL LETTER A WITH ACUTE */\
/* 161='°' */ 	0x00ed, 	/* #LATIN SMALL LETTER I WITH ACUTE */\
/* 162='¢' */ 	0x00f3, 	/* #LATIN SMALL LETTER O WITH ACUTE */\
/* 163='£' */ 	0x00fa, 	/* #LATIN SMALL LETTER U WITH ACUTE */\
/* 164='§' */ 	0x00f1, 	/* #LATIN SMALL LETTER N WITH TILDE */\
/* 165='•' */ 	0x00d1, 	/* #LATIN CAPITAL LETTER N WITH TILDE */\
/* 166='¶' */ 	0x00aa, 	/* #FEMININE ORDINAL INDICATOR */\
/* 167='ß' */ 	0x00ba, 	/* #MASCULINE ORDINAL INDICATOR */\
/* 168='®' */ 	0x00bf, 	/* #INVERTED QUESTION MARK */\
/* 169='©' */ 	0x2310, 	/* #REVERSED NOT SIGN */\
/* 170='™' */ 	0x00ac, 	/* #NOT SIGN */\
/* 171='´' */ 	0x00bd, 	/* #VULGAR FRACTION ONE HALF */\
/* 172='¨' */ 	0x00bc, 	/* #VULGAR FRACTION ONE QUARTER */\
/* 173='≠' */ 	0x00a1, 	/* #INVERTED EXCLAMATION MARK */\
/* 174='Æ' */ 	0x00ab, 	/* #LEFT-POINTING DOUBLE ANGLE QUOTATION MARK */\
/* 175='Ø' */ 	0x00bb, 	/* #RIGHT-POINTING DOUBLE ANGLE QUOTATION MARK */\
/* 176='∞' */ 	0x2591, 	/* #LIGHT SHADE */\
/* 177='±' */ 	0x2592, 	/* #MEDIUM SHADE */\
/* 178='≤' */ 	0x2593, 	/* #DARK SHADE */\
/* 179='≥' */ 	0x2502, 	/* #BOX DRAWINGS LIGHT VERTICAL */\
/* 180='¥' */ 	0x2524, 	/* #BOX DRAWINGS LIGHT VERTICAL AND LEFT */\
/* 181='µ' */ 	0x2561, 	/* #BOX DRAWINGS VERTICAL SINGLE AND LEFT DOUBLE */\
/* 182='∂' */ 	0x2562, 	/* #BOX DRAWINGS VERTICAL DOUBLE AND LEFT SINGLE */\
/* 183='∑' */ 	0x2556, 	/* #BOX DRAWINGS DOWN DOUBLE AND LEFT SINGLE */\
/* 184='∏' */ 	0x2555, 	/* #BOX DRAWINGS DOWN SINGLE AND LEFT DOUBLE */\
/* 185='π' */ 	0x2563, 	/* #BOX DRAWINGS DOUBLE VERTICAL AND LEFT */\
/* 186='∫' */ 	0x2551, 	/* #BOX DRAWINGS DOUBLE VERTICAL */\
/* 187='ª' */ 	0x2557, 	/* #BOX DRAWINGS DOUBLE DOWN AND LEFT */\
/* 188='º' */ 	0x255d, 	/* #BOX DRAWINGS DOUBLE UP AND LEFT */\
/* 189='Ω' */ 	0x255c, 	/* #BOX DRAWINGS UP DOUBLE AND LEFT SINGLE */\
/* 190='æ' */ 	0x255b, 	/* #BOX DRAWINGS UP SINGLE AND LEFT DOUBLE */\
/* 191='ø' */ 	0x2510, 	/* #BOX DRAWINGS LIGHT DOWN AND LEFT */\
/* 192='¿' */ 	0x2514, 	/* #BOX DRAWINGS LIGHT UP AND RIGHT */\
/* 193='¡' */ 	0x2534, 	/* #BOX DRAWINGS LIGHT UP AND HORIZONTAL */\
/* 194='¬' */ 	0x252c, 	/* #BOX DRAWINGS LIGHT DOWN AND HORIZONTAL */\
/* 195='√' */ 	0x251c, 	/* #BOX DRAWINGS LIGHT VERTICAL AND RIGHT */\
/* 196='ƒ' */ 	0x2500, 	/* #BOX DRAWINGS LIGHT HORIZONTAL */\
/* 197='≈' */ 	0x253c, 	/* #BOX DRAWINGS LIGHT VERTICAL AND HORIZONTAL */\
/* 198='∆' */ 	0x255e, 	/* #BOX DRAWINGS VERTICAL SINGLE AND RIGHT DOUBLE */\
/* 199='«' */ 	0x255f, 	/* #BOX DRAWINGS VERTICAL DOUBLE AND RIGHT SINGLE */\
/* 200='»' */ 	0x255a, 	/* #BOX DRAWINGS DOUBLE UP AND RIGHT */\
/* 201='…' */ 	0x2554, 	/* #BOX DRAWINGS DOUBLE DOWN AND RIGHT */\
/* 202=' ' */ 	0x2569, 	/* #BOX DRAWINGS DOUBLE UP AND HORIZONTAL */\
/* 203='À' */ 	0x2566, 	/* #BOX DRAWINGS DOUBLE DOWN AND HORIZONTAL */\
/* 204='Ã' */ 	0x2560, 	/* #BOX DRAWINGS DOUBLE VERTICAL AND RIGHT */\
/* 205='Õ' */ 	0x2550, 	/* #BOX DRAWINGS DOUBLE HORIZONTAL */\
/* 206='Œ' */ 	0x256c, 	/* #BOX DRAWINGS DOUBLE VERTICAL AND HORIZONTAL */\
/* 207='œ' */ 	0x2567, 	/* #BOX DRAWINGS UP SINGLE AND HORIZONTAL DOUBLE */\
/* 208='–' */ 	0x2568, 	/* #BOX DRAWINGS UP DOUBLE AND HORIZONTAL SINGLE */\
/* 209='—' */ 	0x2564, 	/* #BOX DRAWINGS DOWN SINGLE AND HORIZONTAL DOUBLE */\
/* 210='“' */ 	0x2565, 	/* #BOX DRAWINGS DOWN DOUBLE AND HORIZONTAL SINGLE */\
/* 211='”' */ 	0x2559, 	/* #BOX DRAWINGS UP DOUBLE AND RIGHT SINGLE */\
/* 212='‘' */ 	0x2558, 	/* #BOX DRAWINGS UP SINGLE AND RIGHT DOUBLE */\
/* 213='’' */ 	0x2552, 	/* #BOX DRAWINGS DOWN SINGLE AND RIGHT DOUBLE */\
/* 214='÷' */ 	0x2553, 	/* #BOX DRAWINGS DOWN DOUBLE AND RIGHT SINGLE */\
/* 215='◊' */ 	0x256b, 	/* #BOX DRAWINGS VERTICAL DOUBLE AND HORIZONTAL SINGLE */\
/* 216='ÿ' */ 	0x256a, 	/* #BOX DRAWINGS VERTICAL SINGLE AND HORIZONTAL DOUBLE */\
/* 217='Ÿ' */ 	0x2518, 	/* #BOX DRAWINGS LIGHT UP AND LEFT */\
/* 218='⁄' */ 	0x250c, 	/* #BOX DRAWINGS LIGHT DOWN AND RIGHT */\
/* 219='€' */ 	0x2588, 	/* #FULL BLOCK */\
/* 220='‹' */ 	0x2584, 	/* #LOWER HALF BLOCK */\
/* 221='›' */ 	0x258c, 	/* #LEFT HALF BLOCK */\
/* 222='ﬁ' */ 	0x2590, 	/* #RIGHT HALF BLOCK */\
/* 223='ﬂ' */ 	0x2580, 	/* #UPPER HALF BLOCK */\
/* 224='‡' */ 	0x03b1, 	/* #GREEK SMALL LETTER ALPHA */\
/* 225='·' */ 	0x00df, 	/* #LATIN SMALL LETTER SHARP S (GERMAN) */\
/* 226='‚' */ 	0x0393, 	/* #GREEK CAPITAL LETTER GAMMA */\
/* 227='„' */ 	0x03c0, 	/* #GREEK SMALL LETTER PI */\
/* 228='‰' */ 	0x03a3, 	/* #GREEK CAPITAL LETTER SIGMA */\
/* 229='Â' */ 	0x03c3, 	/* #GREEK SMALL LETTER SIGMA */\
/* 230='Ê' */ 	0x00b5, 	/* #MICRO SIGN */\
/* 231='Á' */ 	0x03c4, 	/* #GREEK SMALL LETTER TAU */\
/* 232='Ë' */ 	0x03a6, 	/* #GREEK CAPITAL LETTER PHI */\
/* 233='È' */ 	0x0398, 	/* #GREEK CAPITAL LETTER THETA */\
/* 234='Í' */ 	0x03a9, 	/* #GREEK CAPITAL LETTER OMEGA */\
/* 235='Î' */ 	0x03b4, 	/* #GREEK SMALL LETTER DELTA */\
/* 236='Ï' */ 	0x221e, 	/* #INFINITY */\
/* 237='Ì' */ 	0x03c6, 	/* #GREEK SMALL LETTER PHI */\
/* 238='Ó' */ 	0x03b5, 	/* #GREEK SMALL LETTER EPSILON */\
/* 239='Ô' */ 	0x2229, 	/* #INTERSECTION */\
/* 240='' */ 	0x2261, 	/* #IDENTICAL TO */\
/* 241='Ò' */ 	0x00b1, 	/* #PLUS-MINUS SIGN */\
/* 242='Ú' */ 	0x2265, 	/* #GREATER-THAN OR EQUAL TO */\
/* 243='Û' */ 	0x2264, 	/* #LESS-THAN OR EQUAL TO */\
/* 244='Ù' */ 	0x2320, 	/* #TOP HALF INTEGRAL */\
/* 245='ı' */ 	0x2321, 	/* #BOTTOM HALF INTEGRAL */\
/* 246='ˆ' */ 	0x00f7, 	/* #DIVISION SIGN */\
/* 247='˜' */ 	0x2248, 	/* #ALMOST EQUAL TO */\
/* 248='¯' */ 	0x00b0, 	/* #DEGREE SIGN */\
/* 249='˘' */ 	0x2219, 	/* #BULLET OPERATOR */\
/* 250='˙' */ 	0x00b7, 	/* #MIDDLE DOT */\
/* 251='˚' */ 	0x221a, 	/* #SQUARE ROOT */\
/* 252='¸' */ 	0x207f, 	/* #SUPERSCRIPT LATIN SMALL LETTER N */\
/* 253='˝' */ 	0x00b2, 	/* #SUPERSCRIPT TWO */\
/* 254='˛' */ 	0x25a0, 	/* #BLACK SQUARE */\
/* 255='ˇ' */ 	0x00a0, 	/* #NO-BREAK SPACE */// 

#endif
