/********************************************************
 * filename 864-uni.h
 *
 *  C header file - character cross reference table
 *  Unicode values for codepage 864 indices 128-255
 *  Generated by make-header.pl from CP864.TXT on 2003 Apr 30
 *  Copyright (c) Goldin-Rudahl Associates
 *
 ********************************************************/
// #
// #    Name:     cp864_DOSArabic to Unicode table
// #    Unicode version: 2.0
// #    Table version: 2.00
// #    Table format:  Format A
// #    Date:          04/24/96
// #    Authors:       Lori Brownell <loribr@microsoft.com>
// #                   K.D. Chang    <a-kchang@microsoft.com>
// #    General notes: none
// #
// #    Format: Three tab-separated columns
// #        Column #1 is the cp864_DOSArabic code (in hex)
// #        Column #2 is the Unicode (in hex as 0xXXXX)
// #        Column #3 is the Unicode name (follows a comment sign, '#')
// #
// #    The entries are in cp864_DOSArabic order
// #

#ifndef CP_864_TO_UNI_TAB
#define CP_864_TO_UNI_TAB \
/* 0=' ' */ 	0x0000, 	/* #NULL */\
/* 1=' ' */ 	0x0001, 	/* #START OF HEADING */\
/* 2=' ' */ 	0x0002, 	/* #START OF TEXT */\
/* 3=' ' */ 	0x0003, 	/* #END OF TEXT */\
/* 4=' ' */ 	0x0004, 	/* #END OF TRANSMISSION */\
/* 5=' ' */ 	0x0005, 	/* #ENQUIRY */\
/* 6=' ' */ 	0x0006, 	/* #ACKNOWLEDGE */\
/* 7=' ' */ 	0x0007, 	/* #BELL */\
/* 8=' ' */ 	0x0008, 	/* #BACKSPACE */\
/* 9=' ' */ 	0x0009, 	/* #HORIZONTAL TABULATION */\
/* 10=' ' */ 	0x000a, 	/* #LINE FEED */\
/* 11=' ' */ 	0x000b, 	/* #VERTICAL TABULATION */\
/* 12=' ' */ 	0x000c, 	/* #FORM FEED */\
/* 13=' ' */ 	0x000d, 	/* #CARRIAGE RETURN */\
/* 14=' ' */ 	0x000e, 	/* #SHIFT OUT */\
/* 15=' ' */ 	0x000f, 	/* #SHIFT IN */\
/* 16=' ' */ 	0x0010, 	/* #DATA LINK ESCAPE */\
/* 17=' ' */ 	0x0011, 	/* #DEVICE CONTROL ONE */\
/* 18=' ' */ 	0x0012, 	/* #DEVICE CONTROL TWO */\
/* 19=' ' */ 	0x0013, 	/* #DEVICE CONTROL THREE */\
/* 20=' ' */ 	0x0014, 	/* #DEVICE CONTROL FOUR */\
/* 21=' ' */ 	0x0015, 	/* #NEGATIVE ACKNOWLEDGE */\
/* 22=' ' */ 	0x0016, 	/* #SYNCHRONOUS IDLE */\
/* 23=' ' */ 	0x0017, 	/* #END OF TRANSMISSION BLOCK */\
/* 24=' ' */ 	0x0018, 	/* #CANCEL */\
/* 25=' ' */ 	0x0019, 	/* #END OF MEDIUM */\
/* 26=' ' */ 	0x001a, 	/* #SUBSTITUTE */\
/* 27=' ' */ 	0x001b, 	/* #ESCAPE */\
/* 28=' ' */ 	0x001c, 	/* #FILE SEPARATOR */\
/* 29=' ' */ 	0x001d, 	/* #GROUP SEPARATOR */\
/* 30=' ' */ 	0x001e, 	/* #RECORD SEPARATOR */\
/* 31=' ' */ 	0x001f, 	/* #UNIT SEPARATOR */\
/* 32=' ' */ 	0x0020, 	/* #SPACE */\
/* 33='!' */ 	0x0021, 	/* #EXCLAMATION MARK */\
/* 34='"' */ 	0x0022, 	/* #QUOTATION MARK */\
/* 35='#' */ 	0x0023, 	/* #NUMBER SIGN */\
/* 36='$' */ 	0x0024, 	/* #DOLLAR SIGN */\
/* 37='%' */ 	0x066a, 	/* #ARABIC PERCENT SIGN */\
/* 38='&' */ 	0x0026, 	/* #AMPERSAND */\
/* 39=''' */ 	0x0027, 	/* #APOSTROPHE */\
/* 40='(' */ 	0x0028, 	/* #LEFT PARENTHESIS */\
/* 41=')' */ 	0x0029, 	/* #RIGHT PARENTHESIS */\
/* 42='*' */ 	0x002a, 	/* #ASTERISK */\
/* 43='+' */ 	0x002b, 	/* #PLUS SIGN */\
/* 44=',' */ 	0x002c, 	/* #COMMA */\
/* 45='-' */ 	0x002d, 	/* #HYPHEN-MINUS */\
/* 46='.' */ 	0x002e, 	/* #FULL STOP */\
/* 47='/' */ 	0x002f, 	/* #SOLIDUS */\
/* 48='0' */ 	0x0030, 	/* #DIGIT ZERO */\
/* 49='1' */ 	0x0031, 	/* #DIGIT ONE */\
/* 50='2' */ 	0x0032, 	/* #DIGIT TWO */\
/* 51='3' */ 	0x0033, 	/* #DIGIT THREE */\
/* 52='4' */ 	0x0034, 	/* #DIGIT FOUR */\
/* 53='5' */ 	0x0035, 	/* #DIGIT FIVE */\
/* 54='6' */ 	0x0036, 	/* #DIGIT SIX */\
/* 55='7' */ 	0x0037, 	/* #DIGIT SEVEN */\
/* 56='8' */ 	0x0038, 	/* #DIGIT EIGHT */\
/* 57='9' */ 	0x0039, 	/* #DIGIT NINE */\
/* 58=':' */ 	0x003a, 	/* #COLON */\
/* 59=';' */ 	0x003b, 	/* #SEMICOLON */\
/* 60='<' */ 	0x003c, 	/* #LESS-THAN SIGN */\
/* 61='=' */ 	0x003d, 	/* #EQUALS SIGN */\
/* 62='>' */ 	0x003e, 	/* #GREATER-THAN SIGN */\
/* 63='?' */ 	0x003f, 	/* #QUESTION MARK */\
/* 64='@' */ 	0x0040, 	/* #COMMERCIAL AT */\
/* 65='A' */ 	0x0041, 	/* #LATIN CAPITAL LETTER A */\
/* 66='B' */ 	0x0042, 	/* #LATIN CAPITAL LETTER B */\
/* 67='C' */ 	0x0043, 	/* #LATIN CAPITAL LETTER C */\
/* 68='D' */ 	0x0044, 	/* #LATIN CAPITAL LETTER D */\
/* 69='E' */ 	0x0045, 	/* #LATIN CAPITAL LETTER E */\
/* 70='F' */ 	0x0046, 	/* #LATIN CAPITAL LETTER F */\
/* 71='G' */ 	0x0047, 	/* #LATIN CAPITAL LETTER G */\
/* 72='H' */ 	0x0048, 	/* #LATIN CAPITAL LETTER H */\
/* 73='I' */ 	0x0049, 	/* #LATIN CAPITAL LETTER I */\
/* 74='J' */ 	0x004a, 	/* #LATIN CAPITAL LETTER J */\
/* 75='K' */ 	0x004b, 	/* #LATIN CAPITAL LETTER K */\
/* 76='L' */ 	0x004c, 	/* #LATIN CAPITAL LETTER L */\
/* 77='M' */ 	0x004d, 	/* #LATIN CAPITAL LETTER M */\
/* 78='N' */ 	0x004e, 	/* #LATIN CAPITAL LETTER N */\
/* 79='O' */ 	0x004f, 	/* #LATIN CAPITAL LETTER O */\
/* 80='P' */ 	0x0050, 	/* #LATIN CAPITAL LETTER P */\
/* 81='Q' */ 	0x0051, 	/* #LATIN CAPITAL LETTER Q */\
/* 82='R' */ 	0x0052, 	/* #LATIN CAPITAL LETTER R */\
/* 83='S' */ 	0x0053, 	/* #LATIN CAPITAL LETTER S */\
/* 84='T' */ 	0x0054, 	/* #LATIN CAPITAL LETTER T */\
/* 85='U' */ 	0x0055, 	/* #LATIN CAPITAL LETTER U */\
/* 86='V' */ 	0x0056, 	/* #LATIN CAPITAL LETTER V */\
/* 87='W' */ 	0x0057, 	/* #LATIN CAPITAL LETTER W */\
/* 88='X' */ 	0x0058, 	/* #LATIN CAPITAL LETTER X */\
/* 89='Y' */ 	0x0059, 	/* #LATIN CAPITAL LETTER Y */\
/* 90='Z' */ 	0x005a, 	/* #LATIN CAPITAL LETTER Z */\
/* 91='[' */ 	0x005b, 	/* #LEFT SQUARE BRACKET */\
/* 92='\' */ 	0x005c, 	/* #REVERSE SOLIDUS */\
/* 93=']' */ 	0x005d, 	/* #RIGHT SQUARE BRACKET */\
/* 94='^' */ 	0x005e, 	/* #CIRCUMFLEX ACCENT */\
/* 95='_' */ 	0x005f, 	/* #LOW LINE */\
/* 96='`' */ 	0x0060, 	/* #GRAVE ACCENT */\
/* 97='a' */ 	0x0061, 	/* #LATIN SMALL LETTER A */\
/* 98='b' */ 	0x0062, 	/* #LATIN SMALL LETTER B */\
/* 99='c' */ 	0x0063, 	/* #LATIN SMALL LETTER C */\
/* 100='d' */ 	0x0064, 	/* #LATIN SMALL LETTER D */\
/* 101='e' */ 	0x0065, 	/* #LATIN SMALL LETTER E */\
/* 102='f' */ 	0x0066, 	/* #LATIN SMALL LETTER F */\
/* 103='g' */ 	0x0067, 	/* #LATIN SMALL LETTER G */\
/* 104='h' */ 	0x0068, 	/* #LATIN SMALL LETTER H */\
/* 105='i' */ 	0x0069, 	/* #LATIN SMALL LETTER I */\
/* 106='j' */ 	0x006a, 	/* #LATIN SMALL LETTER J */\
/* 107='k' */ 	0x006b, 	/* #LATIN SMALL LETTER K */\
/* 108='l' */ 	0x006c, 	/* #LATIN SMALL LETTER L */\
/* 109='m' */ 	0x006d, 	/* #LATIN SMALL LETTER M */\
/* 110='n' */ 	0x006e, 	/* #LATIN SMALL LETTER N */\
/* 111='o' */ 	0x006f, 	/* #LATIN SMALL LETTER O */\
/* 112='p' */ 	0x0070, 	/* #LATIN SMALL LETTER P */\
/* 113='q' */ 	0x0071, 	/* #LATIN SMALL LETTER Q */\
/* 114='r' */ 	0x0072, 	/* #LATIN SMALL LETTER R */\
/* 115='s' */ 	0x0073, 	/* #LATIN SMALL LETTER S */\
/* 116='t' */ 	0x0074, 	/* #LATIN SMALL LETTER T */\
/* 117='u' */ 	0x0075, 	/* #LATIN SMALL LETTER U */\
/* 118='v' */ 	0x0076, 	/* #LATIN SMALL LETTER V */\
/* 119='w' */ 	0x0077, 	/* #LATIN SMALL LETTER W */\
/* 120='x' */ 	0x0078, 	/* #LATIN SMALL LETTER X */\
/* 121='y' */ 	0x0079, 	/* #LATIN SMALL LETTER Y */\
/* 122='z' */ 	0x007a, 	/* #LATIN SMALL LETTER Z */\
/* 123='{' */ 	0x007b, 	/* #LEFT CURLY BRACKET */\
/* 124='|' */ 	0x007c, 	/* #VERTICAL LINE */\
/* 125='}' */ 	0x007d, 	/* #RIGHT CURLY BRACKET */\
/* 126='~' */ 	0x007e, 	/* #TILDE */\
/* 127='' */ 	0x007f, 	/* #DELETE */\
/* 128='Ä' */ 	0x00b0, 	/* #DEGREE SIGN */\
/* 129='Å' */ 	0x00b7, 	/* #MIDDLE DOT */\
/* 130='Ç' */ 	0x2219, 	/* #BULLET OPERATOR */\
/* 131='É' */ 	0x221a, 	/* #SQUARE ROOT */\
/* 132='Ñ' */ 	0x2592, 	/* #MEDIUM SHADE */\
/* 133='Ö' */ 	0x2500, 	/* #FORMS LIGHT HORIZONTAL */\
/* 134='Ü' */ 	0x2502, 	/* #FORMS LIGHT VERTICAL */\
/* 135='á' */ 	0x253c, 	/* #FORMS LIGHT VERTICAL AND HORIZONTAL */\
/* 136='à' */ 	0x2524, 	/* #FORMS LIGHT VERTICAL AND LEFT */\
/* 137='â' */ 	0x252c, 	/* #FORMS LIGHT DOWN AND HORIZONTAL */\
/* 138='ä' */ 	0x251c, 	/* #FORMS LIGHT VERTICAL AND RIGHT */\
/* 139='ã' */ 	0x2534, 	/* #FORMS LIGHT UP AND HORIZONTAL */\
/* 140='å' */ 	0x2510, 	/* #FORMS LIGHT DOWN AND LEFT */\
/* 141='ç' */ 	0x250c, 	/* #FORMS LIGHT DOWN AND RIGHT */\
/* 142='é' */ 	0x2514, 	/* #FORMS LIGHT UP AND RIGHT */\
/* 143='è' */ 	0x2518, 	/* #FORMS LIGHT UP AND LEFT */\
/* 144='ê' */ 	0x03b2, 	/* #GREEK SMALL BETA */\
/* 145='ë' */ 	0x221e, 	/* #INFINITY */\
/* 146='í' */ 	0x03c6, 	/* #GREEK SMALL PHI */\
/* 147='ì' */ 	0x00b1, 	/* #PLUS-OR-MINUS SIGN */\
/* 148='î' */ 	0x00bd, 	/* #FRACTION 1/2 */\
/* 149='ï' */ 	0x00bc, 	/* #FRACTION 1/4 */\
/* 150='ñ' */ 	0x2248, 	/* #ALMOST EQUAL TO */\
/* 151='ó' */ 	0x00ab, 	/* #LEFT POINTING GUILLEMET */\
/* 152='ò' */ 	0x00bb, 	/* #RIGHT POINTING GUILLEMET */\
/* 153='ô' */ 	0xfef7, 	/* #ARABIC LIGATURE LAM WITH ALEF WITH HAMZA ABOVE ISOLATED FORM */\
/* 154='ö' */ 	0xfef8, 	/* #ARABIC LIGATURE LAM WITH ALEF WITH HAMZA ABOVE FINAL FORM */\
/* 155='õ' */ 	0x0000, 	/*  */\
/* 156='ú' */ 	0x0000, 	/*  */\
/* 157='ù' */ 	0xfefb, 	/* #ARABIC LIGATURE LAM WITH ALEF ISOLATED FORM */\
/* 158='û' */ 	0xfefc, 	/* #ARABIC LIGATURE LAM WITH ALEF FINAL FORM */\
/* 159='ü' */ 	0x0000, 	/*  */\
/* 160='†' */ 	0x00a0, 	/* #NON-BREAKING SPACE */\
/* 161='°' */ 	0x00ad, 	/* #SOFT HYPHEN */\
/* 162='¢' */ 	0xfe82, 	/* #ARABIC LETTER ALEF WITH MADDA ABOVE FINAL FORM */\
/* 163='£' */ 	0x00a3, 	/* #POUND SIGN */\
/* 164='§' */ 	0x00a4, 	/* #CURRENCY SIGN */\
/* 165='•' */ 	0xfe84, 	/* #ARABIC LETTER ALEF WITH HAMZA ABOVE FINAL FORM */\
/* 166='¶' */ 	0x0000, 	/*  */\
/* 167='ß' */ 	0x0000, 	/*  */\
/* 168='®' */ 	0xfe8e, 	/* #ARABIC LETTER ALEF FINAL FORM */\
/* 169='©' */ 	0xfe8f, 	/* #ARABIC LETTER BEH ISOLATED FORM */\
/* 170='™' */ 	0xfe95, 	/* #ARABIC LETTER TEH ISOLATED FORM */\
/* 171='´' */ 	0xfe99, 	/* #ARABIC LETTER THEH ISOLATED FORM */\
/* 172='¨' */ 	0x060c, 	/* #ARABIC COMMA */\
/* 173='≠' */ 	0xfe9d, 	/* #ARABIC LETTER JEEM ISOLATED FORM */\
/* 174='Æ' */ 	0xfea1, 	/* #ARABIC LETTER HAH ISOLATED FORM */\
/* 175='Ø' */ 	0xfea5, 	/* #ARABIC LETTER KHAH ISOLATED FORM */\
/* 176='∞' */ 	0x0660, 	/* #ARABIC-INDIC DIGIT ZERO */\
/* 177='±' */ 	0x0661, 	/* #ARABIC-INDIC DIGIT ONE */\
/* 178='≤' */ 	0x0662, 	/* #ARABIC-INDIC DIGIT TWO */\
/* 179='≥' */ 	0x0663, 	/* #ARABIC-INDIC DIGIT THREE */\
/* 180='¥' */ 	0x0664, 	/* #ARABIC-INDIC DIGIT FOUR */\
/* 181='µ' */ 	0x0665, 	/* #ARABIC-INDIC DIGIT FIVE */\
/* 182='∂' */ 	0x0666, 	/* #ARABIC-INDIC DIGIT SIX */\
/* 183='∑' */ 	0x0667, 	/* #ARABIC-INDIC DIGIT SEVEN */\
/* 184='∏' */ 	0x0668, 	/* #ARABIC-INDIC DIGIT EIGHT */\
/* 185='π' */ 	0x0669, 	/* #ARABIC-INDIC DIGIT NINE */\
/* 186='∫' */ 	0xfed1, 	/* #ARABIC LETTER FEH ISOLATED FORM */\
/* 187='ª' */ 	0x061b, 	/* #ARABIC SEMICOLON */\
/* 188='º' */ 	0xfeb1, 	/* #ARABIC LETTER SEEN ISOLATED FORM */\
/* 189='Ω' */ 	0xfeb5, 	/* #ARABIC LETTER SHEEN ISOLATED FORM */\
/* 190='æ' */ 	0xfeb9, 	/* #ARABIC LETTER SAD ISOLATED FORM */\
/* 191='ø' */ 	0x061f, 	/* #ARABIC QUESTION MARK */\
/* 192='¿' */ 	0x00a2, 	/* #CENT SIGN */\
/* 193='¡' */ 	0xfe80, 	/* #ARABIC LETTER HAMZA ISOLATED FORM */\
/* 194='¬' */ 	0xfe81, 	/* #ARABIC LETTER ALEF WITH MADDA ABOVE ISOLATED FORM */\
/* 195='√' */ 	0xfe83, 	/* #ARABIC LETTER ALEF WITH HAMZA ABOVE ISOLATED FORM */\
/* 196='ƒ' */ 	0xfe85, 	/* #ARABIC LETTER WAW WITH HAMZA ABOVE ISOLATED FORM */\
/* 197='≈' */ 	0xfeca, 	/* #ARABIC LETTER AIN FINAL FORM */\
/* 198='∆' */ 	0xfe8b, 	/* #ARABIC LETTER YEH WITH HAMZA ABOVE INITIAL FORM */\
/* 199='«' */ 	0xfe8d, 	/* #ARABIC LETTER ALEF ISOLATED FORM */\
/* 200='»' */ 	0xfe91, 	/* #ARABIC LETTER BEH INITIAL FORM */\
/* 201='…' */ 	0xfe93, 	/* #ARABIC LETTER TEH MARBUTA ISOLATED FORM */\
/* 202=' ' */ 	0xfe97, 	/* #ARABIC LETTER TEH INITIAL FORM */\
/* 203='À' */ 	0xfe9b, 	/* #ARABIC LETTER THEH INITIAL FORM */\
/* 204='Ã' */ 	0xfe9f, 	/* #ARABIC LETTER JEEM INITIAL FORM */\
/* 205='Õ' */ 	0xfea3, 	/* #ARABIC LETTER HAH INITIAL FORM */\
/* 206='Œ' */ 	0xfea7, 	/* #ARABIC LETTER KHAH INITIAL FORM */\
/* 207='œ' */ 	0xfea9, 	/* #ARABIC LETTER DAL ISOLATED FORM */\
/* 208='–' */ 	0xfeab, 	/* #ARABIC LETTER THAL ISOLATED FORM */\
/* 209='—' */ 	0xfead, 	/* #ARABIC LETTER REH ISOLATED FORM */\
/* 210='“' */ 	0xfeaf, 	/* #ARABIC LETTER ZAIN ISOLATED FORM */\
/* 211='”' */ 	0xfeb3, 	/* #ARABIC LETTER SEEN INITIAL FORM */\
/* 212='‘' */ 	0xfeb7, 	/* #ARABIC LETTER SHEEN INITIAL FORM */\
/* 213='’' */ 	0xfebb, 	/* #ARABIC LETTER SAD INITIAL FORM */\
/* 214='÷' */ 	0xfebf, 	/* #ARABIC LETTER DAD INITIAL FORM */\
/* 215='◊' */ 	0xfec1, 	/* #ARABIC LETTER TAH ISOLATED FORM */\
/* 216='ÿ' */ 	0xfec5, 	/* #ARABIC LETTER ZAH ISOLATED FORM */\
/* 217='Ÿ' */ 	0xfecb, 	/* #ARABIC LETTER AIN INITIAL FORM */\
/* 218='⁄' */ 	0xfecf, 	/* #ARABIC LETTER GHAIN INITIAL FORM */\
/* 219='€' */ 	0x00a6, 	/* #BROKEN VERTICAL BAR */\
/* 220='‹' */ 	0x00ac, 	/* #NOT SIGN */\
/* 221='›' */ 	0x00f7, 	/* #DIVISION SIGN */\
/* 222='ﬁ' */ 	0x00d7, 	/* #MULTIPLICATION SIGN */\
/* 223='ﬂ' */ 	0xfec9, 	/* #ARABIC LETTER AIN ISOLATED FORM */\
/* 224='‡' */ 	0x0640, 	/* #ARABIC TATWEEL */\
/* 225='·' */ 	0xfed3, 	/* #ARABIC LETTER FEH INITIAL FORM */\
/* 226='‚' */ 	0xfed7, 	/* #ARABIC LETTER QAF INITIAL FORM */\
/* 227='„' */ 	0xfedb, 	/* #ARABIC LETTER KAF INITIAL FORM */\
/* 228='‰' */ 	0xfedf, 	/* #ARABIC LETTER LAM INITIAL FORM */\
/* 229='Â' */ 	0xfee3, 	/* #ARABIC LETTER MEEM INITIAL FORM */\
/* 230='Ê' */ 	0xfee7, 	/* #ARABIC LETTER NOON INITIAL FORM */\
/* 231='Á' */ 	0xfeeb, 	/* #ARABIC LETTER HEH INITIAL FORM */\
/* 232='Ë' */ 	0xfeed, 	/* #ARABIC LETTER WAW ISOLATED FORM */\
/* 233='È' */ 	0xfeef, 	/* #ARABIC LETTER ALEF MAKSURA ISOLATED FORM */\
/* 234='Í' */ 	0xfef3, 	/* #ARABIC LETTER YEH INITIAL FORM */\
/* 235='Î' */ 	0xfebd, 	/* #ARABIC LETTER DAD ISOLATED FORM */\
/* 236='Ï' */ 	0xfecc, 	/* #ARABIC LETTER AIN MEDIAL FORM */\
/* 237='Ì' */ 	0xfece, 	/* #ARABIC LETTER GHAIN FINAL FORM */\
/* 238='Ó' */ 	0xfecd, 	/* #ARABIC LETTER GHAIN ISOLATED FORM */\
/* 239='Ô' */ 	0xfee1, 	/* #ARABIC LETTER MEEM ISOLATED FORM */\
/* 240='' */ 	0xfe7d, 	/* #ARABIC SHADDA MEDIAL FORM */\
/* 241='Ò' */ 	0x0651, 	/* #ARABIC SHADDAH */\
/* 242='Ú' */ 	0xfee5, 	/* #ARABIC LETTER NOON ISOLATED FORM */\
/* 243='Û' */ 	0xfee9, 	/* #ARABIC LETTER HEH ISOLATED FORM */\
/* 244='Ù' */ 	0xfeec, 	/* #ARABIC LETTER HEH MEDIAL FORM */\
/* 245='ı' */ 	0xfef0, 	/* #ARABIC LETTER ALEF MAKSURA FINAL FORM */\
/* 246='ˆ' */ 	0xfef2, 	/* #ARABIC LETTER YEH FINAL FORM */\
/* 247='˜' */ 	0xfed0, 	/* #ARABIC LETTER GHAIN MEDIAL FORM */\
/* 248='¯' */ 	0xfed5, 	/* #ARABIC LETTER QAF ISOLATED FORM */\
/* 249='˘' */ 	0xfef5, 	/* #ARABIC LIGATURE LAM WITH ALEF WITH MADDA ABOVE ISOLATED FORM */\
/* 250='˙' */ 	0xfef6, 	/* #ARABIC LIGATURE LAM WITH ALEF WITH MADDA ABOVE FINAL FORM */\
/* 251='˚' */ 	0xfedd, 	/* #ARABIC LETTER LAM ISOLATED FORM */\
/* 252='¸' */ 	0xfed9, 	/* #ARABIC LETTER KAF ISOLATED FORM */\
/* 253='˝' */ 	0xfef1, 	/* #ARABIC LETTER YEH ISOLATED FORM */\
/* 254='˛' */ 	0x25a0, 	/* #BLACK SQUARE */\
/* 255='ˇ' */ 	0x0000, 	/*  */// 

#endif
