/********************************************************
 * filename 874-uni.h
 *
 *  C header file - character cross reference table
 *  Unicode values for codepage 874 indices 128-255
 *  Generated by make-header.pl from CP874.TXT on 2003 Apr 30
 *  Copyright (c) Goldin-Rudahl Associates
 *
 ********************************************************/
// #
// #    Name:     cp874 to Unicode table
// #    Unicode version: 2.0
// #    Table version: 2.00
// #    Table format:  Format A
// #    Date:          04/15/98
// #
// #    Contact:       cpxlate@microsoft.com
// #
// #    General notes: none
// #
// #    Format: Three tab-separated columns
// #        Column #1 is the cp874 code (in hex)
// #        Column #2 is the Unicode (in hex as 0xXXXX)
// #        Column #3 is the Unicode name (follows a comment sign, '#')
// #
// #    The entries are in cp874 order
// #

#ifndef CP_874_TO_UNI_TAB
#define CP_874_TO_UNI_TAB \
/* 0=' ' */ 	0x0000, 	/* #NULL */\
/* 1=' ' */ 	0x0001, 	/* #START OF HEADING */\
/* 2=' ' */ 	0x0002, 	/* #START OF TEXT */\
/* 3=' ' */ 	0x0003, 	/* #END OF TEXT */\
/* 4=' ' */ 	0x0004, 	/* #END OF TRANSMISSION */\
/* 5=' ' */ 	0x0005, 	/* #ENQUIRY */\
/* 6=' ' */ 	0x0006, 	/* #ACKNOWLEDGE */\
/* 7=' ' */ 	0x0007, 	/* #BELL */\
/* 8=' ' */ 	0x0008, 	/* #BACKSPACE */\
/* 9=' ' */ 	0x0009, 	/* #HORIZONTAL TABULATION */\
/* 10=' ' */ 	0x000a, 	/* #LINE FEED */\
/* 11=' ' */ 	0x000b, 	/* #VERTICAL TABULATION */\
/* 12=' ' */ 	0x000c, 	/* #FORM FEED */\
/* 13=' ' */ 	0x000d, 	/* #CARRIAGE RETURN */\
/* 14=' ' */ 	0x000e, 	/* #SHIFT OUT */\
/* 15=' ' */ 	0x000f, 	/* #SHIFT IN */\
/* 16=' ' */ 	0x0010, 	/* #DATA LINK ESCAPE */\
/* 17=' ' */ 	0x0011, 	/* #DEVICE CONTROL ONE */\
/* 18=' ' */ 	0x0012, 	/* #DEVICE CONTROL TWO */\
/* 19=' ' */ 	0x0013, 	/* #DEVICE CONTROL THREE */\
/* 20=' ' */ 	0x0014, 	/* #DEVICE CONTROL FOUR */\
/* 21=' ' */ 	0x0015, 	/* #NEGATIVE ACKNOWLEDGE */\
/* 22=' ' */ 	0x0016, 	/* #SYNCHRONOUS IDLE */\
/* 23=' ' */ 	0x0017, 	/* #END OF TRANSMISSION BLOCK */\
/* 24=' ' */ 	0x0018, 	/* #CANCEL */\
/* 25=' ' */ 	0x0019, 	/* #END OF MEDIUM */\
/* 26=' ' */ 	0x001a, 	/* #SUBSTITUTE */\
/* 27=' ' */ 	0x001b, 	/* #ESCAPE */\
/* 28=' ' */ 	0x001c, 	/* #FILE SEPARATOR */\
/* 29=' ' */ 	0x001d, 	/* #GROUP SEPARATOR */\
/* 30=' ' */ 	0x001e, 	/* #RECORD SEPARATOR */\
/* 31=' ' */ 	0x001f, 	/* #UNIT SEPARATOR */\
/* 32=' ' */ 	0x0020, 	/* #SPACE */\
/* 33='!' */ 	0x0021, 	/* #EXCLAMATION MARK */\
/* 34='"' */ 	0x0022, 	/* #QUOTATION MARK */\
/* 35='#' */ 	0x0023, 	/* #NUMBER SIGN */\
/* 36='$' */ 	0x0024, 	/* #DOLLAR SIGN */\
/* 37='%' */ 	0x0025, 	/* #PERCENT SIGN */\
/* 38='&' */ 	0x0026, 	/* #AMPERSAND */\
/* 39=''' */ 	0x0027, 	/* #APOSTROPHE */\
/* 40='(' */ 	0x0028, 	/* #LEFT PARENTHESIS */\
/* 41=')' */ 	0x0029, 	/* #RIGHT PARENTHESIS */\
/* 42='*' */ 	0x002a, 	/* #ASTERISK */\
/* 43='+' */ 	0x002b, 	/* #PLUS SIGN */\
/* 44=',' */ 	0x002c, 	/* #COMMA */\
/* 45='-' */ 	0x002d, 	/* #HYPHEN-MINUS */\
/* 46='.' */ 	0x002e, 	/* #FULL STOP */\
/* 47='/' */ 	0x002f, 	/* #SOLIDUS */\
/* 48='0' */ 	0x0030, 	/* #DIGIT ZERO */\
/* 49='1' */ 	0x0031, 	/* #DIGIT ONE */\
/* 50='2' */ 	0x0032, 	/* #DIGIT TWO */\
/* 51='3' */ 	0x0033, 	/* #DIGIT THREE */\
/* 52='4' */ 	0x0034, 	/* #DIGIT FOUR */\
/* 53='5' */ 	0x0035, 	/* #DIGIT FIVE */\
/* 54='6' */ 	0x0036, 	/* #DIGIT SIX */\
/* 55='7' */ 	0x0037, 	/* #DIGIT SEVEN */\
/* 56='8' */ 	0x0038, 	/* #DIGIT EIGHT */\
/* 57='9' */ 	0x0039, 	/* #DIGIT NINE */\
/* 58=':' */ 	0x003a, 	/* #COLON */\
/* 59=';' */ 	0x003b, 	/* #SEMICOLON */\
/* 60='<' */ 	0x003c, 	/* #LESS-THAN SIGN */\
/* 61='=' */ 	0x003d, 	/* #EQUALS SIGN */\
/* 62='>' */ 	0x003e, 	/* #GREATER-THAN SIGN */\
/* 63='?' */ 	0x003f, 	/* #QUESTION MARK */\
/* 64='@' */ 	0x0040, 	/* #COMMERCIAL AT */\
/* 65='A' */ 	0x0041, 	/* #LATIN CAPITAL LETTER A */\
/* 66='B' */ 	0x0042, 	/* #LATIN CAPITAL LETTER B */\
/* 67='C' */ 	0x0043, 	/* #LATIN CAPITAL LETTER C */\
/* 68='D' */ 	0x0044, 	/* #LATIN CAPITAL LETTER D */\
/* 69='E' */ 	0x0045, 	/* #LATIN CAPITAL LETTER E */\
/* 70='F' */ 	0x0046, 	/* #LATIN CAPITAL LETTER F */\
/* 71='G' */ 	0x0047, 	/* #LATIN CAPITAL LETTER G */\
/* 72='H' */ 	0x0048, 	/* #LATIN CAPITAL LETTER H */\
/* 73='I' */ 	0x0049, 	/* #LATIN CAPITAL LETTER I */\
/* 74='J' */ 	0x004a, 	/* #LATIN CAPITAL LETTER J */\
/* 75='K' */ 	0x004b, 	/* #LATIN CAPITAL LETTER K */\
/* 76='L' */ 	0x004c, 	/* #LATIN CAPITAL LETTER L */\
/* 77='M' */ 	0x004d, 	/* #LATIN CAPITAL LETTER M */\
/* 78='N' */ 	0x004e, 	/* #LATIN CAPITAL LETTER N */\
/* 79='O' */ 	0x004f, 	/* #LATIN CAPITAL LETTER O */\
/* 80='P' */ 	0x0050, 	/* #LATIN CAPITAL LETTER P */\
/* 81='Q' */ 	0x0051, 	/* #LATIN CAPITAL LETTER Q */\
/* 82='R' */ 	0x0052, 	/* #LATIN CAPITAL LETTER R */\
/* 83='S' */ 	0x0053, 	/* #LATIN CAPITAL LETTER S */\
/* 84='T' */ 	0x0054, 	/* #LATIN CAPITAL LETTER T */\
/* 85='U' */ 	0x0055, 	/* #LATIN CAPITAL LETTER U */\
/* 86='V' */ 	0x0056, 	/* #LATIN CAPITAL LETTER V */\
/* 87='W' */ 	0x0057, 	/* #LATIN CAPITAL LETTER W */\
/* 88='X' */ 	0x0058, 	/* #LATIN CAPITAL LETTER X */\
/* 89='Y' */ 	0x0059, 	/* #LATIN CAPITAL LETTER Y */\
/* 90='Z' */ 	0x005a, 	/* #LATIN CAPITAL LETTER Z */\
/* 91='[' */ 	0x005b, 	/* #LEFT SQUARE BRACKET */\
/* 92='\' */ 	0x005c, 	/* #REVERSE SOLIDUS */\
/* 93=']' */ 	0x005d, 	/* #RIGHT SQUARE BRACKET */\
/* 94='^' */ 	0x005e, 	/* #CIRCUMFLEX ACCENT */\
/* 95='_' */ 	0x005f, 	/* #LOW LINE */\
/* 96='`' */ 	0x0060, 	/* #GRAVE ACCENT */\
/* 97='a' */ 	0x0061, 	/* #LATIN SMALL LETTER A */\
/* 98='b' */ 	0x0062, 	/* #LATIN SMALL LETTER B */\
/* 99='c' */ 	0x0063, 	/* #LATIN SMALL LETTER C */\
/* 100='d' */ 	0x0064, 	/* #LATIN SMALL LETTER D */\
/* 101='e' */ 	0x0065, 	/* #LATIN SMALL LETTER E */\
/* 102='f' */ 	0x0066, 	/* #LATIN SMALL LETTER F */\
/* 103='g' */ 	0x0067, 	/* #LATIN SMALL LETTER G */\
/* 104='h' */ 	0x0068, 	/* #LATIN SMALL LETTER H */\
/* 105='i' */ 	0x0069, 	/* #LATIN SMALL LETTER I */\
/* 106='j' */ 	0x006a, 	/* #LATIN SMALL LETTER J */\
/* 107='k' */ 	0x006b, 	/* #LATIN SMALL LETTER K */\
/* 108='l' */ 	0x006c, 	/* #LATIN SMALL LETTER L */\
/* 109='m' */ 	0x006d, 	/* #LATIN SMALL LETTER M */\
/* 110='n' */ 	0x006e, 	/* #LATIN SMALL LETTER N */\
/* 111='o' */ 	0x006f, 	/* #LATIN SMALL LETTER O */\
/* 112='p' */ 	0x0070, 	/* #LATIN SMALL LETTER P */\
/* 113='q' */ 	0x0071, 	/* #LATIN SMALL LETTER Q */\
/* 114='r' */ 	0x0072, 	/* #LATIN SMALL LETTER R */\
/* 115='s' */ 	0x0073, 	/* #LATIN SMALL LETTER S */\
/* 116='t' */ 	0x0074, 	/* #LATIN SMALL LETTER T */\
/* 117='u' */ 	0x0075, 	/* #LATIN SMALL LETTER U */\
/* 118='v' */ 	0x0076, 	/* #LATIN SMALL LETTER V */\
/* 119='w' */ 	0x0077, 	/* #LATIN SMALL LETTER W */\
/* 120='x' */ 	0x0078, 	/* #LATIN SMALL LETTER X */\
/* 121='y' */ 	0x0079, 	/* #LATIN SMALL LETTER Y */\
/* 122='z' */ 	0x007a, 	/* #LATIN SMALL LETTER Z */\
/* 123='{' */ 	0x007b, 	/* #LEFT CURLY BRACKET */\
/* 124='|' */ 	0x007c, 	/* #VERTICAL LINE */\
/* 125='}' */ 	0x007d, 	/* #RIGHT CURLY BRACKET */\
/* 126='~' */ 	0x007e, 	/* #TILDE */\
/* 127='' */ 	0x007f, 	/* #DELETE */\
/* 128='Ä' */ 	0x20ac, 	/* #EURO SIGN */\
/* 129='Å' */ 	0x0000, 	/* #UNDEFINED */\
/* 130='Ç' */ 	0x0000, 	/* #UNDEFINED */\
/* 131='É' */ 	0x0000, 	/* #UNDEFINED */\
/* 132='Ñ' */ 	0x0000, 	/* #UNDEFINED */\
/* 133='Ö' */ 	0x2026, 	/* #HORIZONTAL ELLIPSIS */\
/* 134='Ü' */ 	0x0000, 	/* #UNDEFINED */\
/* 135='á' */ 	0x0000, 	/* #UNDEFINED */\
/* 136='à' */ 	0x0000, 	/* #UNDEFINED */\
/* 137='â' */ 	0x0000, 	/* #UNDEFINED */\
/* 138='ä' */ 	0x0000, 	/* #UNDEFINED */\
/* 139='ã' */ 	0x0000, 	/* #UNDEFINED */\
/* 140='å' */ 	0x0000, 	/* #UNDEFINED */\
/* 141='ç' */ 	0x0000, 	/* #UNDEFINED */\
/* 142='é' */ 	0x0000, 	/* #UNDEFINED */\
/* 143='è' */ 	0x0000, 	/* #UNDEFINED */\
/* 144='ê' */ 	0x0000, 	/* #UNDEFINED */\
/* 145='ë' */ 	0x2018, 	/* #LEFT SINGLE QUOTATION MARK */\
/* 146='í' */ 	0x2019, 	/* #RIGHT SINGLE QUOTATION MARK */\
/* 147='ì' */ 	0x201c, 	/* #LEFT DOUBLE QUOTATION MARK */\
/* 148='î' */ 	0x201d, 	/* #RIGHT DOUBLE QUOTATION MARK */\
/* 149='ï' */ 	0x2022, 	/* #BULLET */\
/* 150='ñ' */ 	0x2013, 	/* #EN DASH */\
/* 151='ó' */ 	0x2014, 	/* #EM DASH */\
/* 152='ò' */ 	0x0000, 	/* #UNDEFINED */\
/* 153='ô' */ 	0x0000, 	/* #UNDEFINED */\
/* 154='ö' */ 	0x0000, 	/* #UNDEFINED */\
/* 155='õ' */ 	0x0000, 	/* #UNDEFINED */\
/* 156='ú' */ 	0x0000, 	/* #UNDEFINED */\
/* 157='ù' */ 	0x0000, 	/* #UNDEFINED */\
/* 158='û' */ 	0x0000, 	/* #UNDEFINED */\
/* 159='ü' */ 	0x0000, 	/* #UNDEFINED */\
/* 160='†' */ 	0x00a0, 	/* #NO-BREAK SPACE */\
/* 161='°' */ 	0x0e01, 	/* #THAI CHARACTER KO KAI */\
/* 162='¢' */ 	0x0e02, 	/* #THAI CHARACTER KHO KHAI */\
/* 163='£' */ 	0x0e03, 	/* #THAI CHARACTER KHO KHUAT */\
/* 164='§' */ 	0x0e04, 	/* #THAI CHARACTER KHO KHWAI */\
/* 165='•' */ 	0x0e05, 	/* #THAI CHARACTER KHO KHON */\
/* 166='¶' */ 	0x0e06, 	/* #THAI CHARACTER KHO RAKHANG */\
/* 167='ß' */ 	0x0e07, 	/* #THAI CHARACTER NGO NGU */\
/* 168='®' */ 	0x0e08, 	/* #THAI CHARACTER CHO CHAN */\
/* 169='©' */ 	0x0e09, 	/* #THAI CHARACTER CHO CHING */\
/* 170='™' */ 	0x0e0a, 	/* #THAI CHARACTER CHO CHANG */\
/* 171='´' */ 	0x0e0b, 	/* #THAI CHARACTER SO SO */\
/* 172='¨' */ 	0x0e0c, 	/* #THAI CHARACTER CHO CHOE */\
/* 173='≠' */ 	0x0e0d, 	/* #THAI CHARACTER YO YING */\
/* 174='Æ' */ 	0x0e0e, 	/* #THAI CHARACTER DO CHADA */\
/* 175='Ø' */ 	0x0e0f, 	/* #THAI CHARACTER TO PATAK */\
/* 176='∞' */ 	0x0e10, 	/* #THAI CHARACTER THO THAN */\
/* 177='±' */ 	0x0e11, 	/* #THAI CHARACTER THO NANGMONTHO */\
/* 178='≤' */ 	0x0e12, 	/* #THAI CHARACTER THO PHUTHAO */\
/* 179='≥' */ 	0x0e13, 	/* #THAI CHARACTER NO NEN */\
/* 180='¥' */ 	0x0e14, 	/* #THAI CHARACTER DO DEK */\
/* 181='µ' */ 	0x0e15, 	/* #THAI CHARACTER TO TAO */\
/* 182='∂' */ 	0x0e16, 	/* #THAI CHARACTER THO THUNG */\
/* 183='∑' */ 	0x0e17, 	/* #THAI CHARACTER THO THAHAN */\
/* 184='∏' */ 	0x0e18, 	/* #THAI CHARACTER THO THONG */\
/* 185='π' */ 	0x0e19, 	/* #THAI CHARACTER NO NU */\
/* 186='∫' */ 	0x0e1a, 	/* #THAI CHARACTER BO BAIMAI */\
/* 187='ª' */ 	0x0e1b, 	/* #THAI CHARACTER PO PLA */\
/* 188='º' */ 	0x0e1c, 	/* #THAI CHARACTER PHO PHUNG */\
/* 189='Ω' */ 	0x0e1d, 	/* #THAI CHARACTER FO FA */\
/* 190='æ' */ 	0x0e1e, 	/* #THAI CHARACTER PHO PHAN */\
/* 191='ø' */ 	0x0e1f, 	/* #THAI CHARACTER FO FAN */\
/* 192='¿' */ 	0x0e20, 	/* #THAI CHARACTER PHO SAMPHAO */\
/* 193='¡' */ 	0x0e21, 	/* #THAI CHARACTER MO MA */\
/* 194='¬' */ 	0x0e22, 	/* #THAI CHARACTER YO YAK */\
/* 195='√' */ 	0x0e23, 	/* #THAI CHARACTER RO RUA */\
/* 196='ƒ' */ 	0x0e24, 	/* #THAI CHARACTER RU */\
/* 197='≈' */ 	0x0e25, 	/* #THAI CHARACTER LO LING */\
/* 198='∆' */ 	0x0e26, 	/* #THAI CHARACTER LU */\
/* 199='«' */ 	0x0e27, 	/* #THAI CHARACTER WO WAEN */\
/* 200='»' */ 	0x0e28, 	/* #THAI CHARACTER SO SALA */\
/* 201='…' */ 	0x0e29, 	/* #THAI CHARACTER SO RUSI */\
/* 202=' ' */ 	0x0e2a, 	/* #THAI CHARACTER SO SUA */\
/* 203='À' */ 	0x0e2b, 	/* #THAI CHARACTER HO HIP */\
/* 204='Ã' */ 	0x0e2c, 	/* #THAI CHARACTER LO CHULA */\
/* 205='Õ' */ 	0x0e2d, 	/* #THAI CHARACTER O ANG */\
/* 206='Œ' */ 	0x0e2e, 	/* #THAI CHARACTER HO NOKHUK */\
/* 207='œ' */ 	0x0e2f, 	/* #THAI CHARACTER PAIYANNOI */\
/* 208='–' */ 	0x0e30, 	/* #THAI CHARACTER SARA A */\
/* 209='—' */ 	0x0e31, 	/* #THAI CHARACTER MAI HAN-AKAT */\
/* 210='“' */ 	0x0e32, 	/* #THAI CHARACTER SARA AA */\
/* 211='”' */ 	0x0e33, 	/* #THAI CHARACTER SARA AM */\
/* 212='‘' */ 	0x0e34, 	/* #THAI CHARACTER SARA I */\
/* 213='’' */ 	0x0e35, 	/* #THAI CHARACTER SARA II */\
/* 214='÷' */ 	0x0e36, 	/* #THAI CHARACTER SARA UE */\
/* 215='◊' */ 	0x0e37, 	/* #THAI CHARACTER SARA UEE */\
/* 216='ÿ' */ 	0x0e38, 	/* #THAI CHARACTER SARA U */\
/* 217='Ÿ' */ 	0x0e39, 	/* #THAI CHARACTER SARA UU */\
/* 218='⁄' */ 	0x0e3a, 	/* #THAI CHARACTER PHINTHU */\
/* 219='€' */ 	0x0000, 	/* #UNDEFINED */\
/* 220='‹' */ 	0x0000, 	/* #UNDEFINED */\
/* 221='›' */ 	0x0000, 	/* #UNDEFINED */\
/* 222='ﬁ' */ 	0x0000, 	/* #UNDEFINED */\
/* 223='ﬂ' */ 	0x0e3f, 	/* #THAI CURRENCY SYMBOL BAHT */\
/* 224='‡' */ 	0x0e40, 	/* #THAI CHARACTER SARA E */\
/* 225='·' */ 	0x0e41, 	/* #THAI CHARACTER SARA AE */\
/* 226='‚' */ 	0x0e42, 	/* #THAI CHARACTER SARA O */\
/* 227='„' */ 	0x0e43, 	/* #THAI CHARACTER SARA AI MAIMUAN */\
/* 228='‰' */ 	0x0e44, 	/* #THAI CHARACTER SARA AI MAIMALAI */\
/* 229='Â' */ 	0x0e45, 	/* #THAI CHARACTER LAKKHANGYAO */\
/* 230='Ê' */ 	0x0e46, 	/* #THAI CHARACTER MAIYAMOK */\
/* 231='Á' */ 	0x0e47, 	/* #THAI CHARACTER MAITAIKHU */\
/* 232='Ë' */ 	0x0e48, 	/* #THAI CHARACTER MAI EK */\
/* 233='È' */ 	0x0e49, 	/* #THAI CHARACTER MAI THO */\
/* 234='Í' */ 	0x0e4a, 	/* #THAI CHARACTER MAI TRI */\
/* 235='Î' */ 	0x0e4b, 	/* #THAI CHARACTER MAI CHATTAWA */\
/* 236='Ï' */ 	0x0e4c, 	/* #THAI CHARACTER THANTHAKHAT */\
/* 237='Ì' */ 	0x0e4d, 	/* #THAI CHARACTER NIKHAHIT */\
/* 238='Ó' */ 	0x0e4e, 	/* #THAI CHARACTER YAMAKKAN */\
/* 239='Ô' */ 	0x0e4f, 	/* #THAI CHARACTER FONGMAN */\
/* 240='' */ 	0x0e50, 	/* #THAI DIGIT ZERO */\
/* 241='Ò' */ 	0x0e51, 	/* #THAI DIGIT ONE */\
/* 242='Ú' */ 	0x0e52, 	/* #THAI DIGIT TWO */\
/* 243='Û' */ 	0x0e53, 	/* #THAI DIGIT THREE */\
/* 244='Ù' */ 	0x0e54, 	/* #THAI DIGIT FOUR */\
/* 245='ı' */ 	0x0e55, 	/* #THAI DIGIT FIVE */\
/* 246='ˆ' */ 	0x0e56, 	/* #THAI DIGIT SIX */\
/* 247='˜' */ 	0x0e57, 	/* #THAI DIGIT SEVEN */\
/* 248='¯' */ 	0x0e58, 	/* #THAI DIGIT EIGHT */\
/* 249='˘' */ 	0x0e59, 	/* #THAI DIGIT NINE */\
/* 250='˙' */ 	0x0e5a, 	/* #THAI CHARACTER ANGKHANKHU */\
/* 251='˚' */ 	0x0e5b, 	/* #THAI CHARACTER KHOMUT */\
/* 252='¸' */ 	0x0000, 	/* #UNDEFINED */\
/* 253='˝' */ 	0x0000, 	/* #UNDEFINED */\
/* 254='˛' */ 	0x0000, 	/* #UNDEFINED */\
/* 255='ˇ' */ 	0x0000, 	/* #UNDEFINED */
#endif
