/* 
 *	filename GcpStateChart.h
 *	generated on Mon Jun  2 16:45:42 ICT 2008
 *
 *      Copyright Kurt Rudahl and Sally Goldin
 *
 *	THIS IS A PARTLY GENERATED FILE - SEE BELOW
 *
 *	All rights are reserved. Copying or other reproduction of
 *	this program except for archival purposes is prohibited
 *	without the prior written consent of Goldin-Rudahl Associates.
 *
 *			  RESTRICTED RIGHTS LEGEND
 *
 *	Use, duplication, or disclosure by the U.S. Government
 *	is subject to restrictions as set forth in
 *	paragraph (b) (3) (B) of the Rights in Technical
 *	Data and Computer Software clause in DAR 7-104.9(a).
 *
 *	The moral right of the copyright holder is hereby asserted
 *
 *******************************************************************
 *
 *		INSTRUCTIONS FOR MODIFYING THIS FILE
 *
 *	This file was generated by Yamdat, and may be re-generated
 *	in future.
 *
 *	You can make changes to this file (for example by adding
 *	action code) which will not be lost during future 
 *	regeneration by understanding the following rules:
 *
 *	1. For .cpp files, the following are preserved by the
 *	   generation process:
 *	     a. The file header block, up to the first blank
 *		line or end-of-comment (asterisk-slash)
 *	     b. All #includes
 *	     c. All method bodies
 *	     d. All sections of code surrounded by
 *			-KEEP BEGIN-
 *			-KEEP END-
 *
 *	2. For .cpp files, the following are overwritten by the
 *	   generation process, except as above:
 *	     a. All method declarations including their documentation
 *		block
 *	     b. Everything else is deleted.
 *
 *	3. For .h files, the following are preserved by the
 *	   generation process:
 *	     a. Everything up to the beginning of the class declaration
 *	     b. All sections of code surrounded by
 *			-KEEP BEGIN-
 *			-KEEP END-
 *
 *	4. For .h files, the following are overwritten by the
 *	   generation process, except as above:
 *	     a. The class declaration and anything following it.
 *
 *********************************************************************
 *	&dol;Id: &dol;
 *	&dol;Log: &dol;
 *********************************************************************
 */

#ifndef GCPSTATECHART_H
#define GCPSTATECHART_H
 

/* State table created 2008-06-02 by Dia2StateTbl.pl
 * from GcpStateChart.dia
 *
 * GENERATED FILE -- DO NOT EDIT
 */
typedef enum 
    {
    GCPS_END_,	    GCPS_START_,
    GCPS_VP1ACCEPT,	    GCPS_VP1OVERVIEW,
    GCPS_VP1VP2OVERVIEW,	    GCPS_VP2ACCEPT,
    GCPS_VP2OVERVIEW,	    GCPS_VPACCEPT,
    GCPS_VPACCEPTK,	    GCPS_VPOVERVIEW
    } GCP_STATE;

#define GCP_STATE_NAMES\
    "GCPS_END_",	    "GCPS_START_",\
    "GCPS_VP1ACCEPT",	    "GCPS_VP1OVERVIEW",\
    "GCPS_VP1VP2OVERVIEW",	    "GCPS_VP2ACCEPT",\
    "GCPS_VP2OVERVIEW",	    "GCPS_VPACCEPT",\
    "GCPS_VPACCEPTK",	    "GCPS_VPOVERVIEW"

typedef enum 
    {
    GCPE_F1F10,	    GCPE_F9,
    GCPE_POINTSEL,	    GCPE_RCLICK_VP1,
    GCPE_RCLICK_VP2,	    GCPE_RGN1SEL,
    GCPE_RGN1SELK,	    GCPE_RGN1SEL_VP1,
    GCPE_RGN1SEL_VP2,	    GCPE_RGN2SEL,
    GCPE_RGN2SEL_VP1,	    GCPE_RGN2SEL_VP2,
    GCPE_START,	    GCPE_START2
    } GCP_EVENT;

#define GCP_EVENT_NAMES\
    "GCPE_F1F10",	    "GCPE_F9",\
    "GCPE_POINTSEL",	    "GCPE_RCLICK_VP1",\
    "GCPE_RCLICK_VP2",	    "GCPE_RGN1SEL",\
    "GCPE_RGN1SELK",	    "GCPE_RGN1SEL_VP1",\
    "GCPE_RGN1SEL_VP2",	    "GCPE_RGN2SEL",\
    "GCPE_RGN2SEL_VP1",	    "GCPE_RGN2SEL_VP2",\
    "GCPE_START",	    "GCPE_START2"

#define GCP_TRANSITIONS\
/*                                   GCPE_F1F10              GCPE_F9        GCPE_POINTSEL      GCPE_RCLICK_VP1      GCPE_RCLICK_VP2         GCPE_RGN1SEL        GCPE_RGN1SELK     GCPE_RGN1SEL_VP1     GCPE_RGN1SEL_VP2         GCPE_RGN2SEL     GCPE_RGN2SEL_VP1     GCPE_RGN2SEL_VP2           GCPE_START          GCPE_START2 */\
/* GCPS_END_             */                  -1,                  -2,                  -3,                  -4,                  -5,                  -6,                  -7,                  -8,                  -9,                 -10,                 -11,                 -12,                 -13,                 -14,\
/* GCPS_START_           */                 -15,                 -16,                 -17,                 -18,                 -19,                 -20,                 -21,                 -22,                 -23,                 -24,                 -25,                 -26,     GCPS_VPOVERVIEW, GCPS_VP1VP2OVERVIEW,\
/* GCPS_VP1ACCEPT        */           GCPS_END_,      GCPS_VP1ACCEPT,      GCPS_VP2ACCEPT,    GCPS_VP1OVERVIEW,    GCPS_VP2OVERVIEW,                 -27,                 -28,                 -29,                 -30,                 -31,                 -32,                 -33,                 -34,                 -35,\
/* GCPS_VP1OVERVIEW      */           GCPS_END_,                 -36,                 -37,                 -38, GCPS_VP1VP2OVERVIEW,                 -39,                 -40,      GCPS_VP1ACCEPT,      GCPS_VP2ACCEPT,                 -41,                 -42,                 -43,                 -44,                 -45,\
/* GCPS_VP1VP2OVERVIEW   */           GCPS_END_,                 -46,                 -47,                 -48,                 -49,    GCPS_VP2OVERVIEW,                 -50,                 -51,                 -52,    GCPS_VP1OVERVIEW,                 -53,                 -54,                 -55,                 -56,\
/* GCPS_VP2ACCEPT        */           GCPS_END_,      GCPS_VP1ACCEPT,      GCPS_VP1ACCEPT,    GCPS_VP1OVERVIEW,    GCPS_VP2OVERVIEW,                 -57,                 -58,                 -59,                 -60,                 -61,                 -62,                 -63,                 -64,                 -65,\
/* GCPS_VP2OVERVIEW      */           GCPS_END_,                 -66,                 -67, GCPS_VP1VP2OVERVIEW,                 -68,                 -69,                 -70,                 -71,                 -72,                 -73,      GCPS_VP1ACCEPT,      GCPS_VP2ACCEPT,                 -74,                 -75,\
/* GCPS_VPACCEPT         */           GCPS_END_,       GCPS_VPACCEPT,       GCPS_VPACCEPT,     GCPS_VPOVERVIEW,                 -76,                 -77,                 -78,                 -79,                 -80,                 -81,                 -82,                 -83,                 -84,                 -85,\
/* GCPS_VPACCEPTK        */           GCPS_END_,      GCPS_VPACCEPTK,      GCPS_VPACCEPTK,     GCPS_VPOVERVIEW,                 -86,                 -87,                 -88,                 -89,                 -90,                 -91,                 -92,                 -93,                 -94,                 -95,\
/* GCPS_VPOVERVIEW       */           GCPS_END_,                 -96,                 -97,                 -98,                 -99,       GCPS_VPACCEPT,      GCPS_VPACCEPTK,                -100,                -101,                -102,                -103,                -104,                -105,                -106

//STATES GCPS_END_ GCPS_START_ GCPS_VP1ACCEPT GCPS_VP1OVERVIEW GCPS_VP1VP2OVERVIEW GCPS_VP2ACCEPT GCPS_VP2OVERVIEW GCPS_VPACCEPT GCPS_VPACCEPTK GCPS_VPOVERVIEW
#endif
